### ISSUE TITLE
User can request to disable organisation

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#101]
Once User request to disable organization we should trigger email to all member of organization informing 
"x" user has requested to disable organization. If they Y person want it to active they need to reach out to us at contact@pythonexpress.in. In case Y person ask us to keep it active we will remove X person to be member of organization.

**Comment by shubhamgupta2021** [comment]
@vnbang2003, Instead of deleting the organization I will suggest, user can leave the organization and if the user is admin/owner of the organization, he can pass the ownership to another user in the organization

**Comment by vnbang2003** [comment]
By delete we mean disable
