### ISSUE TITLE
Workshop Feedback button should be display once work is completed

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#102]
We need to display feedback button for each completed workshop.
It should be displayed for both Presenter/Requester.
Once Feedback is given we need to disable display of button

**Comment by vnbang2003** [comment]
@shankisg Can you please add this button as you are aware of Url. It should be easy fix.

**Comment by shankisg** [comment]
@vnbang2003 
Will do.  Where should the feedback button  be displayed.

**Comment by vnbang2003** [comment]
@shankisg In workshop list page we need to display button on the status.

**Comment by vnbang2003** [comment]
Closing it as issue #161  has action button logic explained.
