### ISSUE TITLE
Footer of about us page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#103]
The content of about us page is overlapping the footer.
@harisibrahimkv  : Can you please fix this ?
![screen shot 2015-10-24 at 6 46 40 pm](https://cloud.githubusercontent.com/assets/316253/10710630/b040c45a-7a7f-11e5-999a-92faa5411b64.png)

**Comment by harisibrahimkv** [comment]
Ehh. @Praseetha-KR Is this something to do with the styling? Or should I reduce the content?

**Comment by ChillarAnand** [comment]
Looks like its fixed.

**Comment by vnbang2003** [comment]
@harisibrahimkv @Praseetha-KR Can you please verify if fixed let's close it.

**Comment by Praseetha-KR** [comment]
Its fixed in 2915ac39fbf1e2263ca19e50c2dd5b3673ed3cf0, but that branch is work-in-progress

**Comment by vnbang2003** [comment]
Closing this issue as it's been fixed.
