### ISSUE TITLE
Dashboard page break in case profile is not created

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#105]
If user has not created profile page the dashboard break . We need to redirect user to create profile page in case it profile object is not created.
@staranjeet This bug is for you are you check in has broken functionality .

**Comment by staranjeet** [comment]
Whenever I login, I get this error. I am not sure whether this error is specific to my machine or everyone is facing it.

`AttributeError at /accounts/login/`
`'tuple' object has no attribute 'encode'`

**Comment by vnbang2003** [comment]
I have seen it.

**Comment by staranjeet** [comment]
PR #107
