### ISSUE TITLE
Ensure slug uniqueness of profile model

### ISSUE THREAD

**Issue by theskumar** [pythonindia/wye#112]
Slug requirement on profile is not enforced to be unique properly: https://travis-ci.org/pythonindia/wye/builds/87602968
Options:
1. Remove the slug property and use `user.username` instead everywhere
2. Override `save()` of Profile Model, so that slug is always created.

**Comment by theskumar** [comment]
@staranjeet can you please have a look at this issue, which is also causing the tests to fail. Let me know your thoughts?

**Comment by staranjeet** [comment]
@theskumar : While using post_save signal, what if instead of 
`profile, created = Profile.objects.get_or_create(user=instance)`
we do it like this 
`profile, created = Profile.objects.get_or_create(user=instance, slug=user.username)`

**Comment by theskumar** [comment]
@staranjeet Basically, I am trying to understand, is there any reason to de-normalize the `slug` to `Profile` model.  Denormalization comes with it own issues:

What if the username get changed for some user the slug will become inconsistent. I think ideally we should allow for change in `username`. Now that said, since user is able to pick their own username while signing up, we need to make we properly validate the username to be url friendly. 

If we don't have any strong reason to denormalize, i think we should remove the slug from profile.

cc: @vnbang2003

**Comment by theskumar** [comment]
```
profile, created = Profile.objects.get_or_create(user=instance, slug=user.username)
```
Here a new user profile will be created if the username is changed.
```
profile, created = Profile.objects.get_or_create(user=instance)
if created:
  profile.slug=user.username
  profile.save()
```
I think this would make more sense.

**Comment by theskumar** [comment]
I thinking more on the line of having slug a class property.

```
@property 
def slug(self):
  return slugify(self.user.username)
```

**Comment by staranjeet** [comment]
What about `USERNAME_FIELD`? Will that work with this?
I think it should because username is always unique. What my concern is that it is normally a string describing the name of a field. Of property I am not aware.
@theskumar

**Comment by theskumar** [comment]
@staranjeet I think the `USERNAME_FIELD` is required on a `AUTH_USER_MODEL` (i.e, `User`)not on profile. Am I missing on something here?

**Comment by theskumar** [comment]
For now, i'm going with removing the `slug` field from the database and calculate it when needed, so that all the test passes in master to close #114.

But I am keeping this issue open for further discussion. To understand the problem better.

**Comment by vnbang2003** [comment]
@staranjeet Can you help with this ?

**Comment by theskumar** [comment]
The current implementation in the master branch takes care of this so, i'm closing this. Please re-open as necessary.
