### ISSUE TITLE
Rewrite Breadcrumbs 

### ISSUE THREAD

**Issue by ultimatecoder** [pythonindia/wye#113]
**Problem:** The present breadcrumbs are not properly visible. It is conflicting with other elements at view side.

**Image:**
![problem_breadcrumbs](https://cloud.githubusercontent.com/assets/3719122/10753713/eb113192-7cb8-11e5-94a7-e0423499ba58.png)

**Solution:**:
Use [Bootstrap Breadcrumb classes](http://getbootstrap.com/components/#breadcrumbs).

**Comment by curioswati** [comment]
Ok. I will fix it.
