### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#114]
I see test case are failing and build is failing.
https://travis-ci.org/pythonindia/wye/builds/87602968

@theskumar : Can you look into  ?

**Comment by theskumar** [comment]
@vnbang2003 The build is failing due to code got introduced in `master` before merging the testing PR. Here is ticket for the bug, with possible solution: https://github.com/pythonindia/wye/issues/112

**Comment by vnbang2003** [comment]
@theskumar Can we assign to person who introduced the bug so they fix it. Let fix the build.
