### ISSUE TITLE
Static page to display different kind of workshop

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#118]
We need to add static page to display different kind of workshop we conduct and if possible topic we will cover.
1) Python 101
2) Get started with Django
3) get Started with Flask
4) Scipy 101
etc.

@Praseetha-KR : Can you help with design the page ?

**Comment by Praseetha-KR** [comment]
Added `/workshops_info` in 5256be89da3c2b6fcca11b1b35fa2cd294ff3d23

**Comment by vnbang2003** [comment]
@Praseetha-KR We need to add topic  with subtitle
for example Python101 will have below topics
1.    Introduction & language basics
2.    Some background to Python
3.    Value, types, expressions, and statements
4.    Data types (Lists, tuples, and dictionaries)
5.    Functions
6.    Class
7.    Regular Expression
8.    New style class
9.    Decorator, Generator
10.  Files, modules, directories and packages
11.  Special keywords like with, future
12.  Unittest

**Comment by kracekumar** [comment]
On Fri, Oct 30, 2015 at 10:36 AM, Vijay <notifications@github.com> wrote:

> @Praseetha-KR <https://github.com/Praseetha-KR> We need to add topic with
> subtitle
> for example Python101 will have below topics
> 1. Introduction & language basics
> 2. Some background to Python
> 3. Value, types, expressions, and statements
> 4. Data types (Lists, tuples, and dictionaries)
> 5. Functions
> 6. Class
> 7. Regular Expression
> 8. New style class
> 9. Decorator, Generator
> 10. Files, modules, directories and packages
> 11. Special keywords like with, future
> 12. Unittest
>

2p:

Please check the topics, it isn't practically feasible to cover 7, 9, 11,
12 and doesn't classify as 101.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/118#issuecomment-152416188>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by vnbang2003** [comment]
@kracekumar I just shared example so @Praseetha-KR can design page. I even think it to much to cover the topic.  Let discuss what we will cover in 1 and 2 days workshop in mailing list .
