### ISSUE TITLE
Profile Dashbaord Page show error

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#123]
@staranjeet Am getting this error below error when i open http://localhost:8000/profile/dashboard/

FieldError at /profile/dashboard/

Cannot resolve keyword 'slug' into field. Choices are: interested_locations, interested_sections, mobile, user, user_id, usertype

Request Method: 	GET
Request URL: 	http://localhost:8000/profile/dashboard/
Django Version: 	1.8.5
Exception Type: 	FieldError
Exception Value: 	

Cannot resolve keyword 'slug' into field. Choices are: interested_locations, interested_sections, mobile, user, user_id, usertype

Exception Location: 	/Users/vijaybang/Work/wye-env/lib/python3.4/site-packages/django/db/models/sql/query.py in names_to_path, line 1397

**Comment by staranjeet** [comment]
Have you run the migrations? because slug field is now removed.

**Comment by vnbang2003** [comment]
The error message says we are referring slug fields in code which doesn't exists.
Can you update you local clean and run migrations once and see if you face same issue.

**Comment by staranjeet** [comment]
I think I have figured out the problem. slug field is removed from Profile model, but in the detail view we are still referencing that. The possible workaround for this is, pass primary key now. Changes that it will require are 

`url(r'^(?P<pk>[0-9]+)/$', views.ProfileView.as_view(),name='profile_page')`
In the `get_context_data` of `ProfileView` model, 

`pk = self.kwargs['pk']
self.object = models.Profile.objects.get(user_id=pk)`

If this Ok, then I will send a PR which fixes this.

**Comment by vnbang2003** [comment]
/profile/dashboard/ uses UserDashboard view so i don't see reason why it should effect it ?

**Comment by staranjeet** [comment]
but in the urls, `profile_page` is above `dashboard` urls. So may be it is catching it over there. I have seen every other piece of code in the profiles app. Only reason I could figure out is either this url or the migration which removes slug field from the model and instead lists it as a cached property are the possible reason. 
Its working fine on my system.

**Comment by vnbang2003** [comment]
I found couple of issue 1) Url name (2) ProfielView. 
I will fix them. Thanks
