### ISSUE TITLE
Add TestCase for Workshop and Organisation

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#124]
We need to add more test case for workshop and organisaiton
We have too many option and out code is not covering all the option.

**Comment by vnbang2003** [comment]
@theskumar Can you work on this ?

**Comment by theskumar** [comment]
I can't any see testcase for workshop/organisation in the codebase. It seems we just need to add the test cases. Title of this issue need to be altered? @vnbang2003

**Comment by vnbang2003** [comment]
@theskumar Can we please disable testing section for build . It really getting confusion to accept any pull request . Once we fix testcase we can enable it back

**Comment by ultimatecoder** [comment]
@theskumar  @vnbang2003  Are we expecting for Unit testing or Functional testing or Both for Organization and Workshop? I think we should split task of Testing for Organization, Workshop, Profile.

**Comment by vnbang2003** [comment]
@ultimatecoder I agree with you but keep this PR open .
For profile we already have tescase #152 . 
I would say let send pull request for each tescase possible and keep improvising test coverage.
Once we reach to 80% mark we can close this PR.

**Comment by ultimatecoder** [comment]
@vnbang2003  Okay. 
**First Point:** Issue #152 Not containing description related to some methods of Profile model. I think it will be irrelevant to add description to that Issue. I am Creating new issue for that.

**Second Point:** As Unit testing and Functional testing is different part. Person like me don't have experience in Functional testing but having little of Unit testing. So, It will be great to make separate issue with little more description on type of testing. It will result as, The person can work on unit testing rather then caring about functional and we will be able to find which part of testing is remaining.

**Comment by vnbang2003** [comment]
@ultimatecoder The goal of this PR is to add testcase and remainder to us to know we have to fix it.
I would request you to keep send Pull request with Testcase(unit or functional)and we will keep accept it. Is not this a simple process ?

**Comment by ultimatecoder** [comment]
@vnbang2003 Yes, It is simple process but I am much familiar with the workflow of this framework but think about new person who is coming first time to contribute this project. Various experience level will be there. From novice to expert. So, it would be great to at least at some more description to PR on what steps to follow, which part is completed and which part is remaining.

* Little Example:

1 Write Unit test: Description of the packages to must use, Some example test case scenarios which must be included in the code, etc.

2 Write Functional Test: Description of the packages, Must included scenarios, accepted coverage level etc.

Now, Suppose we merged PR containing test case of Unit test then scratch the first point. This will improve the person who is looking issues every time that what is already done and what is still remaining.

**Comment by ultimatecoder** [comment]
@vnbang2003 : I can see the **Testing** label but in issues it is not attached to. It will be good to update. Thanks!
