### ISSUE TITLE
Workshop create

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#125]
When user request for workshop  in create form we need to display fields with below criteria
1) Organization : He belong to and he created to(Only Active organisation)
2)Location value can be taken from Organisation Models hence we can skip display
3) Status by default is "Requested" hence we should not display it.

@shankisg : Can you take it as high priority to fix the issue. The same logic needs to applied for edit also.

**Comment by shankisg** [comment]
Ok

**Comment by vnbang2003** [comment]
@shankisg Present logic assume user will belong to one Organization but we will have scenario where one user can belong to more than one organization.
Example: X user of Open source community can be in touch with n organization hence he will create n organization.  
Can you please make changes accordingly ?

**Comment by shankisg** [comment]
I can do the change. 
Is it possible for on user to be tutor as well as organisation user.

**Comment by vnbang2003** [comment]
Yes user can have multiple roles(Types).
I have explained who all can create/edit workshops in PR #139 .
Even Let display proper error message instead of just 403 page.

**Comment by shankisg** [comment]
@vnbang2003 

**Confusion** If a user could belong to multiple organisation, how do we know for which organisation the workshop is created **1) Organization : He belong to and he created to(Only Active organisation)**

**Comment by vnbang2003** [comment]
@shankisg User can have multiple roles
I as a lecture can conduct python workshop in my college right ?
In the requester list we just display organization logged in user is member of.(Organisation.objects.filter(
            user=self.request.user)

**Comment by shankisg** [comment]
Fix implemented commit  # 75ddd948ed6f231c13180d52776381ee2fe21000

**Comment by shankisg** [comment]
@vnbang2003 pls close this issue

**Comment by vnbang2003** [comment]
@shankisg We need to get HTML email stuff also in hence it open.
