### ISSUE TITLE
Profile Page fields

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#129]
In the Profile view page we will not be displaying phone number and email id.

**Comment by ultimatecoder** [comment]
@vnbang2003  Well, I believe we should give choice to user. Consider example of Github profile. User might want to put their this profile as reference of their work.

**Comment by vnbang2003** [comment]
@ultimatecoder I agree with you . Can you work on this once you complete signup page ?

**Comment by ultimatecoder** [comment]
@vnbang2003  By giving choices for displaying their phone number and email to their profile? or Just removing them from the profile view?

**Comment by vnbang2003** [comment]
Let user decide if they want to share email and phone number.

**Comment by vnbang2003** [comment]
@ultimatecoder Is this done ?

**Comment by ultimatecoder** [comment]
@vnbang2003  Yes. You had merged it yesterday. You can close this.
