### ISSUE TITLE
Once user login we need to redirect to /dashboard/ page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#131]
Once user login we need to redirect to /dashboard/ page . Presently it redirect to / page.
We need to change configuration in settings.py  but the changes are impacting test script hence @theskumar can you take it up and work so you can change your testcases also.

@theskumar if possible can you add example test script for creation of organization or profile so other contributors start using it a benchmark

**Comment by theskumar** [comment]
New issue created for adding the testcase at https://github.com/pythonindia/wye/issues/152
