### ISSUE TITLE
Align user avatar with text in menu

### ISSUE THREAD

**Issue by kirang89** [pythonindia/wye#133]
![home___pythonexpress](https://cloud.githubusercontent.com/assets/1074304/10866571/57a6b7e2-805a-11e5-899d-a8637bf62912.png)

**Comment by vnbang2003** [comment]
Is it similar to #128  ?

**Comment by kirang89** [comment]
Ah yes it is.

On Sun, Nov 1, 2015, at 10:09 AM, Vijay wrote:
> Is it similar to #128[1]  ?


> — Reply to this email directly or view it on GitHub[2].


>

--
Kiran Gangadharan
http://kirang.in


Links:

  1. https://github.com/pythonindia/wye/issues/128
  2. https://github.com/pythonindia/wye/issues/133#issuecomment-152793696

**Comment by vnbang2003** [comment]
Can we make this PR and duplicate and close it?

**Comment by kirang89** [comment]
Please go ahead.


On Sun, Nov 1, 2015, at 11:04 AM, Vijay wrote:
> Can we make this PR and duplicate and close it?


> — Reply to this email directly or view it on GitHub[1].


>

--
Kiran Gangadharan
http://kirang.in
 


Links:

  1. https://github.com/pythonindia/wye/issues/133#issuecomment-152795034
