### ISSUE TITLE
Irrelevant location options for local organisations

### ISSUE THREAD

**Issue by kirang89** [pythonindia/wye#134]
![organisation___pythonexpress](https://cloud.githubusercontent.com/assets/1074304/10866609/8e7cdc9a-805c-11e5-94e3-36624f4af883.png)

**Comment by vnbang2003** [comment]
@kirang89 We need to display all the location name as we are not sure which location college belongs to.Let me know if i missed something.

**Comment by kirang89** [comment]
@vnbang2003 I mean, shouldn't we have 2 elements, one for the city, and one for the area ?

**Comment by vnbang2003** [comment]
i will be adding easy of add location feature once that done it will resolve this problem also.
