### ISSUE TITLE
Add datepicker in workshop creation view

### ISSUE THREAD

**Issue by kirang89** [pythonindia/wye#138]
![pythonexpress](https://cloud.githubusercontent.com/assets/1074304/10866926/eb027252-806d-11e5-9f37-e4bf4ca31c3d.png)

**Comment by vnbang2003** [comment]
@curioswati Can you help with this ?

**Comment by curioswati** [comment]
ok @vnbang2003 . I am working on this.

**Comment by shankisg** [comment]
@vnbang2003 @curioswati 

The datepicker is already their. Due to some changes in base.html it was not working, I have fix that issue. 

Fix is available in this pull request https://github.com/pythonindia/wye/pull/145
