### ISSUE TITLE
Admin landing page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#14]
In the Page
Admin should see total workshop with different status(Pagination: 10) 
Admin Should see total conference with different region(Pagination: 10) 
Admin should see button where he can send email to by button click(Requester/Accepted) who haven't shared feedback to workshop conducted.
Admin should be add new regional leads(State wise)

**Comment by vnbang2003** [comment]
Duplicate to #12 hence closing it

**Comment by staranjeet** [comment]
what does conference with different region mean here?

**Comment by kracekumar** [comment]
:-) It is workshop not conference.

**Comment by staranjeet** [comment]
@kracekumar : +1:

**Comment by staranjeet** [comment]
this issue is related with #12 , #13 . How should I go for the html part. I mean for each user type I have a different set of context variables. So I should display all of them with in a single page or any other approach can be used ? 
@kracekumar @vnbang2003

**Comment by kracekumar** [comment]
@staranjeet have a different view for each of use case.

**Comment by staranjeet** [comment]
So this will involve writing `DetailView` for each usertype and then calling each view as MyView.as_view(). Is this right?

**Comment by kracekumar** [comment]
No, From html there will be relevant buttons/urls to take to relevant pages. Yes detail view with different urls.

**Comment by kracekumar** [comment]
Other approach is to have single view with different template to each type.
