### ISSUE TITLE
Forbidden to edit details for workshop that I created

### ISSUE THREAD

**Issue by kirang89** [pythonindia/wye#141]
I get a ```403 Forbidden``` when I try to edit the details of a workshop that I created.

![pythonexpress](https://cloud.githubusercontent.com/assets/1074304/10868416/ee9f6dd4-80b3-11e5-8aa7-c7a4965ff7d5.jpg)

**Comment by shankisg** [comment]
@kirang89 

You need to be member of an organisation(requester) to edit any workshop requested by that organisation.

In other words you can only edit workshop related to the organisation you belong to.

**Comment by shankisg** [comment]
Pls close this issue, if working as discussed in my previous comment.

**Comment by vnbang2003** [comment]
@kirang89 I agree with @shankisg . You can edit workshop only which you are part of.
@shankisg Can you confirm if regional lead and admin user are allowed to edit workshop ?

**Comment by shankisg** [comment]
@vnbang2003 
regional lead and admin are not allowed. Let me know if you want to change the logic

**Comment by kirang89** [comment]
@vnbang2003 @shankisg If that's the case, we should mention that when the user tries to share feedback instead of just showing a 403. 

The behaviour was confusing and that's why I raised the issue.

**Comment by vnbang2003** [comment]
Disabled edit option for tutor
