### ISSUE TITLE
Wrong title/data?

### ISSUE THREAD

**Issue by kirang89** [pythonindia/wye#144]
I'm not sure what the actual bug is –– either the title "My workshops" is incorrect or the list should only show the workshops that I have accepted

![pythonexpress](https://cloud.githubusercontent.com/assets/1074304/10868501/0e34ae78-80b6-11e5-9d5d-8a6462ddda88.jpg)

**Comment by vnbang2003** [comment]
yes it's a bug . We need to add that filter in workshop listing page.

**Comment by vnbang2003** [comment]
@kirang89 Even requester can see workshops hence i think we can just better text.
If Lead/Admin logins we need to show different set of workshop.

**Comment by kirang89** [comment]
@vnbang2003 In that case, a user should only be able to view workshops that haven't been accepted yet, in which case, we don't need the column for sharing feedback at all. Am I correct here or have I missed something ?

**Comment by vnbang2003** [comment]
Feedback button is only for workshop completed and feedback not shared. We need to implement logic to control the display.

**Comment by vnbang2003** [comment]
We have feedback button issue #102 . @kirang89 Can we close this ?

**Comment by kirang89** [comment]
Yes, please go ahead.
