### ISSUE TITLE
Add testcase for user registration flow

### ISSUE THREAD

**Issue by theskumar** [pythonindia/wye#152]

**Comment by aniketmaithani** [comment]
@theskumar correct me if I am wrong. You mean to say we need to mock the whole `flow` of the `signup` process upto the point where user signs in once his email id is confirmed and he can login using the chosen email and password?

**Comment by aniketmaithani** [comment]
#217 does this.

**Comment by theskumar** [comment]
@aniketmaithani yes.

**Comment by aniketmaithani** [comment]
Though it is merged can you still look at PR #217 and let me know if there are any upgrades/changes you want? as I am thinking of writing a test-case for "REQUIRED" fields also
