### ISSUE TITLE
IRC, Gitter channel for developers 

### ISSUE THREAD

**Issue by ultimatecoder** [pythonindia/wye#153]
**Description:**

1 **Gitter, IRC** channel where developers can talk on issues, new development. Let us be there and talk there every time.

2 **Weekly Hangouts** where we all can share their problems with the tool, communication gap and other improvements they think is required. This will improve our quality, we have to think in one direction. Presently there are many confusions regarding the flow (personally I have) it would be great to let reviewer share their problems they are facing during code review, contributor facing problems during the coding, PR and will try to fill the gap by discussion. @vnbang2003  @theskumar @kracekumar  requesting you to give your thoughts here.

**Comment by vnbang2003** [comment]
@ultimatecoder Let take discussion in mailing list .
Am +1 for weekly hangout i had proposed it before but got carried out with other things and lost track.
I propose Wednesday evening 7.30 PM hangout if it works for everyone.

Adding @shankisg @vanishan for discussion

**Comment by ultimatecoder** [comment]
@vnbang2003  Mailing list okay.
On Weekly hangout I personally believe because it will held on every week, I think Weekend is more preferable. I will be agree with the time. I personally don't have issue with Wednesday. 
If I clear you, were you insisting Wednesday for every hangout or just for first Hangout?

**Comment by vnbang2003** [comment]
I have started thread in mailing list lets discuss there.
@ultimatecoder you can drop email to me for meeting i can help join hangout and help you understand my point of view.

**Comment by ultimatecoder** [comment]
@vnbang2003  Got that!

**Comment by vnbang2003** [comment]
@ultimatecoder As this software is completely volunteer driven from different location . Workflow are gone change very often for next few days as we all have different plan in mind. 
Let plan to get this product very professional is only thing i can request.

**Comment by ultimatecoder** [comment]
:+1:

**Comment by vnbang2003** [comment]
Closing this as we can discuss this things in mailing list
