### ISSUE TITLE
Regional lead addition/removal

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#157]
When admin user add new regional lead/update we should update usertype object in the user profile page.If user is removed from all regional lead position we need to remove his role as userType.

**Comment by mukeshthawani** [comment]
I am working on this.

**Comment by vnbang2003** [comment]
@mukeshthawani Are you working on it. If yes will assign it to you.
Please take a look at testcase coverage also

**Comment by mukeshthawani** [comment]
Yeah, I am working on this.

**Comment by vnbang2003** [comment]
I  guess this bug is fixed . @curioswati Can you confirm please ?

**Comment by curioswati** [comment]
yes @vnbang2003 It was fixed in #171 .
