### ISSUE TITLE
Profile validation

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#158]
Presently we validate if profile object is created and assume profile created has userType selected.
We need to change validation in all places to make sure profile object has usertype role selected.

**Comment by ultimatecoder** [comment]
@vnbang2003  and Redirect user to profile edit page if user-type is null.

**Comment by vnbang2003** [comment]
@ultimatecoder Yes

**Comment by vnbang2003** [comment]
@ultimatecoder : If requirement is clear do you want to take it up as it a blocker for beta release ?

**Comment by ultimatecoder** [comment]
![](http://cdn.memegenerator.net/instances/400x/31291114.jpg)

**Comment by vnbang2003** [comment]
Can we get fix today . As we are almost ready for going live.

**Comment by vnbang2003** [comment]
@ultimatecoder this is only issue open for v0.1 can you please update us on status so we can plan for beta release ?

**Comment by vnbang2003** [comment]
@ultimatecoder Any progress on this?
