### ISSUE TITLE
Display of workshop action button

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#161]
In the workshop list page Presently we display 4-5 button depending on status only.
We need to add more logic to show button based on logged in person
1) Hold button should be displayed only if logged-in person is member of workshop requested organisation and workshop is not completed.
2) Requested button should be display only if logged-in person is member of workshop requested organisation and workshop is in hold status.
3) Reject : Only to presenter who had accepted the workshop.
5) Feedback button should be display only to presenter who has accepted workshop and members of organisation who requested workshop and display on after the end date of workshop.
   Ex: if workshop is completed on 3-Nov , we should display feedback button from 4-Nov.
5) Accepted workshop to all login user if workshop is in requested status.

**Comment by vnbang2003** [comment]
@curioswati Can you help us with this ?

**Comment by curioswati** [comment]
ok. I am doing it.

**Comment by curioswati** [comment]
I can do it in evening, will that be okay?

**Comment by vnbang2003** [comment]
@curioswati that should be problem. If anything is not clear let us know.

**Comment by curioswati** [comment]
ok.

**Comment by vnbang2003** [comment]
Can we get fix today . As we are almost ready for going live.

**Comment by curioswati** [comment]
Yes, I will complete it by today evening.

**Comment by curioswati** [comment]
Sorry, but I am stuck at a point and will not be able to implement this fix today. I was trying to write template tags so that I could access session info in model, but facing some issue. If some one else can do it, please take it.

**Comment by vnbang2003** [comment]
@curioswati we just need to define 4 variable in view's context and display button accordingly.
Let me know if you still available to take it up else i will complete it.

**Comment by vnbang2003** [comment]
@curioswati I just check in example for custom tag with 2 variable . Were you thinking of similar ?
https://github.com/pythonindia/wye/commit/ccb20865f1a35b6f4b0673bb3b1162a94048503d
Do you want to continue and finish the PR ?

**Comment by curioswati** [comment]
yes exactly, I was trying the same. But When I called the method in templatetag, It says, boolean can't be called. I was calling the model property from the template tag, but I see, you have defined them in the template tag itself. Yes I can do it this way.

**Comment by vnbang2003** [comment]
Cool than i will wait for PR from you .

**Comment by curioswati** [comment]
@vnbang2003 where can I get the workshop completion date from?

**Comment by vnbang2003** [comment]
where can I get the workshop completion date from?: if workshop expected_date is less than today we count it as complete.

**Comment by curioswati** [comment]
yes I did that only.
