### ISSUE TITLE
Regional Lead can assign workshop

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#162]
Regional Leads should be able to add workshop to tutor who had contacted them offline.
Regional lead can assign workshop only region they belong to.
This button should be displayed only to regional Lead.

**Comment by shankisg** [comment]
Started working on it

**Comment by vnbang2003** [comment]
@shankisg Let me know if any info is required on this

**Comment by shankisg** [comment]
Ok

**Comment by shankisg** [comment]
@vnbang2003 where you are planning to provide assign option to regional leads. As current create/edit workshop form doesn't have tutors select field .

**Comment by vnbang2003** [comment]
Yes we are planning to provide assign option to tutor(user)

**Comment by shankisg** [comment]
How you are planning to provide assign option, 
 
- whether it would be inside create/update workshop form
- Or somewhere you are planning to give dropdown to select tutor.

According to that I will plan the implementation.

**Comment by vnbang2003** [comment]
@shankisg I haven't given thought on this yet on how UI will look. Can you come up with UI so we can decide after looking in UI.

**Comment by vnbang2003** [comment]
@shankisg Are you working on it ? If yes assign to your self please

**Comment by shankisg** [comment]
I do not have assign permission

**Comment by vnbang2003** [comment]
You should have now.

**Comment by vnbang2003** [comment]
Let start pushing a bit we need to release version 0.2 by Jan 25th.

**Comment by shankisg** [comment]
Ok,will add PR in next few days

**Comment by shankisg** [comment]
@vnbang2003 what about providing a multiselect field for selecting presenter in workshop edit form, this field will be displayed for only usertype regional lead.

Your thought?

**Comment by vnbang2003** [comment]
@shankisg Over the period once user base grow multiselect with be tough to manage.

**Comment by shankisg** [comment]
@vnbang2003 without having a multiselect how you can allow Regional lead to select multiple tutors.

May be later we can add search capability to multiselect.

**Comment by vnbang2003** [comment]
@shankisg  Sounds good
