### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#17]
We need to add form with below fields
1) Email Id
2) Phone number
3)Dropdown with option (Profile, Workshop, Organisation and others)
4) Text Box 

Once user click on submit button it should send email to admins and Regional Leads with form details.

**Comment by vnbang2003** [comment]
@harisibrahimkv Can you please help with content ?

**Comment by vnbang2003** [comment]
@staranjeet Can you help us create the functionality ?

**Comment by staranjeet** [comment]
yeah. What should be the fields here? Name, Email, Address, Mobile, Inquiry msg, and captcha.
Also This involves creating a new model, so that model should be in profiles app or any other app?

**Comment by vnbang2003** [comment]
Yes captcha is good point.
I was think no need to store this ? but if email goes in spam it better to store ?
@theskumar @kirang89 @kracekumar what do you guys think ?

**Comment by staranjeet** [comment]
yeah suggestions please. I was a little busy yesterday so I missed the hangout. When are we having the next hangout?

**Comment by kirang89** [comment]
@vnbang2003  Quick comments:
- Why do we need to ask for phone number ? The lesser information we ask for, the better, IMO.

Apart from this, I agree with Vijay about not having to store any information. The page is just a simple interface for reaching out to us.

**Comment by vnbang2003** [comment]
The purpose of the page is to get feedback . It a simple interface with more details to understand what feedback they want to give to us.
Mobile number can be optional this might help us create account for them if they face trouble creating account .

**Comment by kirang89** [comment]
> Dropdown with option (Profile, Workshop, Organisation and others)

The reason I asked about the purpose of the page was because of the above option. 

> Mobile number can be optional this might help us create account for them if they face trouble creating account .

Agreed. So, now if someone has trouble creating an account, the dropdown should be optional as well right ?

**Comment by vnbang2003** [comment]
agreed

**Comment by vnbang2003** [comment]
@staranjeet Can it be possible to get this feature asap so we can get it live along with beta version live ?

**Comment by staranjeet** [comment]
when is beta going to be live?

**Comment by vnbang2003** [comment]
Probably Wednesday or Thursday . We are just wait for E2E machine provision.

**Comment by DESHRAJ** [comment]
Great. :)

**Comment by staranjeet** [comment]
I have pushed a branch contact-us-page and created a diff from my [master](https://github.com/staranjeet/wye/pull/1).

Some things needs discussion or suggestions:

* Placed the views code in profiles app. Is it ok or not?
* The mail template is not beautified. The details are listed on individual lines.
* Taking name, email, content, query_topic and mobile(optional). Labels needs to be changed.
* The thank you message and url (after a response is saved)
* What captcha should I use? I was thinking of recaptcha and for that we need to register [here](https://www.google.com/recaptcha/admin#list)

@vnbang2003

**Comment by vnbang2003** [comment]
Placed the views code in profiles app. Is it ok or not?  
- For now it ok.

The mail template is not beautified. The details are listed on individual lines. 

- Have provided feedback to extend now. @harisibrahimkv Can help you generate it
- We need two email (1) to Python express team(regional leads and admins (2) to requester

Taking name, email, content, query_topic and mobile(optional). Labels needs to be changed.
- Can we even verify email id and mobile number verificaiton in form validation ?

The thank you message and url (after a response is saved)
What captcha should I use? I was thinking of recaptcha and for that we need to register here

@kracekumar Can you help register for recaptcha ?
@staranjeet Let us know what you need once registered ?

**Comment by staranjeet** [comment]
Have updated the [pull](https://github.com/staranjeet/wye/commit/5924f06ff5e002b2ef0339d90f3b0db5c57bac2b) as per the changes suggested by @vnbang2003 .

What does verifying email and mobile means here? Do you means sending mail and message to the one who is trying to contact us, so that we can verify is he/she authentic?

I think for a contact us page, this should not be required. Captcha is enough to prevent us from bots. We need to discuss regarding this.
 @kracekumar @vnbang2003 @kirang89

**Comment by vnbang2003** [comment]
I mean validate email and mobile else we will be listed soon in spams.
For not let move on without captcha. Let open issue and plan for v0.2

**Comment by staranjeet** [comment]
so u mean a individual clean function for mobile and email which checks the following
* clean_mobile : whether the entered mobile number is of 10 digits or 11 for landline
* clean_email : checks whether the email is a valid email through regex.
?

**Comment by vnbang2003** [comment]
yep

**Comment by staranjeet** [comment]
ok i will do this. rest all changes are fine. If so then I will create a PR from wye's master now?

**Comment by vnbang2003** [comment]
@staranjeet Have shared feedback on your branch.

**Comment by staranjeet** [comment]
yeah I have seen. I will do the changes.
