### ISSUE TITLE
Add Captcha for contact us page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#173]
We need to add captcha for contact us form to make sure we are not spammed.

**Comment by vnbang2003** [comment]
@staranjeet  Do you want to plan around this libraries and come up with best and easy compatibility library ?
https://github.com/alsoicode/django-simple-math-captcha
https://github.com/mbi/django-simple-captcha

If you more time you can do play around with all the libraries
https://www.djangopackages.com/grids/g/captcha/

**Comment by staranjeet** [comment]
I think `django-simple-math-captcha` is apt here. It does not require any changes in settings file nor any migrations. It is simple add, subtract and multiply. Infact we can pass in the error messages also like

`captcha = MathCaptchaField(error_messages={
        'invalid': 'Wrong answer. Check your maths and try again',
        })
`


The initial captcha: 
![initialcaptcha](https://cloud.githubusercontent.com/assets/4302268/11163732/348b27ba-8b00-11e5-8d3b-88b47d237431.png)

When a wrong answer is entered
![wronganswer](https://cloud.githubusercontent.com/assets/4302268/11163739/4ddd9a04-8b00-11e5-9380-03ac266af88e.png)

When a non integer(whole number) is entered
![string](https://cloud.githubusercontent.com/assets/4302268/11163743/5cc230ac-8b00-11e5-8a32-7357fa7fc0b9.png)

The above error messages can be customized
I am submitting a PR with this captcha field as of now. Let me know if any changes are required

**Comment by staranjeet** [comment]
#177
