### ISSUE TITLE
Social accounts missing in SignUp

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/wye#178]
Login page allows social accounts like `Github`, `Google`, `Twitter`, signup page doesn't have those options.

![screen shot 2015-11-15 at 12 54 54 pm](https://cloud.githubusercontent.com/assets/311929/11167797/00941a14-8b98-11e5-95bf-1a9fbd925502.png)
![screen shot 2015-11-15 at 12 55 08 pm](https://cloud.githubusercontent.com/assets/311929/11167801/068eab82-8b98-11e5-8a48-f43c720f1556.png)

**Comment by vnbang2003** [comment]
@DESHRAJ Can you fix it . This is blocking us to go live ?

**Comment by DESHRAJ** [comment]
ok sure @vnbang2003, I will fix this by today itself.

**Comment by DESHRAJ** [comment]
Fixed in https://github.com/pythonindia/wye/pull/187

**Comment by vnbang2003** [comment]
@DESHRAJ Are you working on it ?

**Comment by DESHRAJ** [comment]
@vnbang2003 I am not working on it currently.
