### ISSUE TITLE
Sign Up page doesn't indicate mandatory fields with '*'

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/wye#179]
![screen shot 2015-11-15 at 12 57 01 pm](https://cloud.githubusercontent.com/assets/311929/11167803/50c3de52-8b98-11e5-810f-a850b950801e.png)

**Comment by vnbang2003** [comment]
@DESHRAJ Can you even take it and it minor change ?

**Comment by DESHRAJ** [comment]
ok sure. I will fix this one too. :)

**Comment by DESHRAJ** [comment]
Fixed in https://github.com/pythonindia/wye/pull/187
