### ISSUE TITLE
FAQ/help page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#18]
We should add static page which explain how to use the system.
Probably ReadMe page will do but add it a placeholder for now.

**Comment by saideepchandg** [comment]
@vnbang2003 - Is anyone working on this? It would be good to have a small team who can prepare list of probable questions and then share with the wider team. Your thoughts please.

**Comment by vnbang2003** [comment]
I had discuss this with @harisibrahimkv during last F2F meetup . I don't recall those question now.
@harisibrahimkv do you recall ?

**Comment by harisibrahimkv** [comment]
Oh hmm... Let me try to jot them down:

1. Why are we doing free workshops?
2. Can anyone be a tutor?
3. Is there a selection process?
4. Can anyone attend the workshops?
5. Whom do you conduct workshops for?
6. Can I use this to organize a training in my company?
7. How do I become a tutor?
8. How do I organize a workshop?
9. Is there any kind of fee associated with PythonExpress?
10. What is the motive?

That's just off the top of my head. Please add/edit.

**Comment by saideepchandg** [comment]
As we have the exhaustive list, we can consider grouping them based on where they can come from.

**_From Tutors_**
- Is physical presence required or I can do remotely via skype, hangouts etc.?
- What is the typical duration of these workshops ?
- I accepted the workshop and now I cant make it? Is it ok to cancel ? How early should I intimate?
- Can I get help in the form of decks or sample code which can be re-used ?
- Do we get any remuneration for doing the workshops? Or any kind of reimbursement (e.g. transport allowing for reaching the venue?)
- I get the idea and love sharing knowledge but what is in it for me?
- Are there any guidelines while accepting the workshops or can I adopt my style of teaching?

**Comment by vnbang2003** [comment]
Looks very good set of questions

**Comment by vnbang2003** [comment]
@vanishan @kracekumar Can you help with FAQ page ?
