### ISSUE TITLE
Migrate Data from Old server to new server

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#182]
We need to move data from old server to new server.

**Comment by vnbang2003** [comment]
@vigneshsarma @kracekumar let take on our hands this issue so we can plan it.

**Comment by vnbang2003** [comment]
@vigneshsarma Can you help me get dump from old server so i can start plan for migrate to new server ?

**Comment by vigneshsarma** [comment]
@vnbang2003 have mailed you the backup.

**Comment by vnbang2003** [comment]
@vigneshsarma Thanks i have received. Let me see if we can migrate all the data.
At the same time can we disable beta.pythonexpress.in

**Comment by vigneshsarma** [comment]
Since we setup ssl, `beta` is gone.
