### ISSUE TITLE
Email Template footer Details 

### ISSUE THREAD

**Issue by vigneshstack** [pythonindia/wye#188]
Update footer details on email template 

Follow on Twitter   Friend on Facebook   Forward to Friend 
Copyright © *|CURRENT_YEAR|* *|LIST:COMPANY|*, All rights reserved. 
*|IFNOT:ARCHIVE_PAGE|* *|LIST:DESCRIPTION|* 

Our mailing address is: 
*|HTML:LIST_ADDRESS_HTML|* *|END:IF|*
unsubscribe from this list   update subscription preferences

**Comment by vnbang2003** [comment]
@Praseetha-KR Can you help with this ?
