### ISSUE TITLE
Workshop request should allowed only for future dates

### ISSUE THREAD

**Issue by saideepchandg** [pythonindia/wye#194]
I am able to request for a workshop in a past date. See the image below:
![image](https://cloud.githubusercontent.com/assets/11366144/11202328/f7da3d2e-8d0c-11e5-953f-cf9dcb5cde09.png)

We may need to discuss how far in future (after 1 week?) can a workshop be requested. But back-dated workshop shouldnt be allowed.

**Comment by vnbang2003** [comment]
We need to allowed users to request workshop only for future dates. I think we need atleast 2 weeks time to plan for workshop as we need to find the volunteer for that regions.

@staranjeet Can you help with this . Requesting you as @shankisg is on vacation ?

**Comment by staranjeet** [comment]
Sure I will do it.

**Comment by staranjeet** [comment]
@vnbang2003 : so this involves writing a clean function for date field, which raises an error if the input date is less than 2 weeks from present date or in past. Right?

**Comment by vnbang2003** [comment]
@staranjeet Yep

**Comment by vnbang2003** [comment]
It pushed to production hence closing ti

**Comment by saideepchandg** [comment]
@staranjeet - Do you want to have a look at the message? 
- Message is repeated twice
- expected_date can be removed
Other than that, it works. 
![image](https://cloud.githubusercontent.com/assets/11366144/11221499/7c6d1588-8d8b-11e5-946e-f502ce77749f.png)

**Comment by staranjeet** [comment]
@saideepchandg : That message will repeat twice in every field. But I have fixed the `expected_date` one. 
PR #203

**Comment by vnbang2003** [comment]
@staranjeet i think we can remove form.errors  in template workshop_create.html.
field level error  and form.error is duplicating error message.
Can you give a try ?

**Comment by staranjeet** [comment]
Yeah I will have a look.

**Comment by staranjeet** [comment]
removing `{{form.errors}}` works. submitting a PR which removes all such case but per app, so that it becomes easy for you to review.

**Comment by staranjeet** [comment]
submitted PR #205 and #206 . Let me know if this ok, so that I can do it for other apps as well?
