### ISSUE TITLE
Delhi and other Cities not mentioned

### ISSUE THREAD

**Issue by satyaakam** [pythonindia/wye#195]
Hi,

After registering as a tutor i am not seeing Delhi and many other cities in the drop down menu.

one suggestion is if we can capture both State and City name that would be good.

**Comment by vnbang2003** [comment]
@satyaakam Presently system has 29 states and 38 cities added.
As Dehli was Union territory we missing it.I have fixed it by adding it to system.
Please help us point to different cities we can add to system .

**Comment by satyaakam** [comment]
this list is a good start https://en.wikipedia.org/wiki/List_of_cities_in_India_by_population

**Comment by vnbang2003** [comment]
@satyaakam Thanks this will help a lot.

**Comment by lavish205** [comment]
Hi
Can't we use Google Places API, as an autocomplete API as it will list all the places and also provide us details related to that place eg: latitude longitude?

**Comment by vnbang2003** [comment]
Will be opening PR with more details to allow user to enter any new location.
