### ISSUE TITLE
What is the Max number of particpants ?

### ISSUE THREAD

**Issue by saideepchandg** [pythonindia/wye#200]
Can we agree on the number of max participants? Currently, it seems to allow 2147483647 - which I feel is quite large number.
![image](https://cloud.githubusercontent.com/assets/11366144/11221696/7dde4aee-8d8c-11e5-800f-04a1cc6f073a.png)

**Comment by vnbang2003** [comment]
@curioswati Can you please help with this . Max we should allow per workshop is 100.
@kracekumar @kirang89 @theskumar What do you guys think  ?

**Comment by kirang89** [comment]
100 sounds good.

**Comment by kracekumar** [comment]
+1 for 100.

On Fri, Nov 20, 2015 at 1:10 AM, Kiran Gangadharan <notifications@github.com
> wrote:

> 100 sounds good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/200#issuecomment-158172191>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by theskumar** [comment]
This is case where user is trying to hack into the system, instead of making a genuine workshop with realistic number of participants.

100 seems to me quite limiting, I think it should be 1000 or 2000, instead of 2,147,483,647.

**Comment by curioswati** [comment]
Ok, I will do it by evening @vnbang2003.
