### ISSUE TITLE
Organization | 'Delete' button not working & taking to update page

### ISSUE THREAD

**Issue by saideepchandg** [pythonindia/wye#202]
I click on the delete button in below screen.
![image](https://cloud.githubusercontent.com/assets/11366144/11221993/05de5118-8d8e-11e5-93d1-1fd643ca56aa.png)
It takes me to this screen instead of deleting.
![image](https://cloud.githubusercontent.com/assets/11366144/11222024/248de11e-8d8e-11e5-8a71-bb407dc6ace9.png)

If we are allowing deletion of Organization, what are the checks before deleting?
- No Workshops?
- Has requisite access to delete or any member in the organization can delete?

**Comment by bhanuvrat** [comment]
@saideepchandg 
soft delete with flipping the `is_active` flag would be more appropriate. 

Imagine a begrudged co-ordinator maliciously purging the records of all workshops held at their former place of work.

**Comment by vnbang2003** [comment]
Pull request is out hence closing it
