### ISSUE TITLE
Profile pictures showing broken images

### ISSUE THREAD

**Issue by satyaakam** [pythonindia/wye#208]
Hi,
profile images after upload are not seen in the profile the path i see is http://beta.pythonexpress.in/media/images/

looks like we are uploading to Heroku directly not storing to file storages like S3,these will be reset after every push to Heroku.

-Satya

**Comment by vnbang2003** [comment]
We already have bug for it . https://github.com/pythonindia/wye/issues/197
Marking it as duplicate
