### ISSUE TITLE
Contact Form - Default 'Your Name' and 'Your email'

### ISSUE THREAD

**Issue by saideepchandg** [pythonindia/wye#209]
This is not an issue but enhancement. I think it would be good to default name and email if the user is logged in. 
Any thoughts on whether we would like to allow the user to update those fields after it defaults?
![image](https://cloud.githubusercontent.com/assets/11366144/11302164/bffab0fc-8fc1-11e5-8d35-667e8ee9d922.png)

**Comment by vnbang2003** [comment]
@saideepchandg Let keep it simple but looks good idea.
We can plan it for v0.3 this

**Comment by saideepchandg** [comment]
@vnbang2003 - Agreed. This is not priority.

**Comment by vnbang2003** [comment]
@ultimatecoder Can you help with this ?

**Comment by RishabhJain2018** [comment]
@vnbang2003 @ChillarAnand @kracekumar Can I pick up this issue?

**Comment by vnbang2003** [comment]
@RishabhJain2018 Just drop message saying "you are working on it" and short description on how you want to implement it.

**Comment by ashishjain28** [comment]
@vnbang2003 I am working on it. I will check if the user is already logged in before creating the form instance, if yes then I will initialize the name and email field.
