### ISSUE TITLE
Added tutor in CC once workshop is accepted

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#212]
We should show profile pic of the tutor in the twitter message once tutor accept any workshop.

@harisibrahimkv @kracekumar @theskumar @kirang89  What do you guys think ?

**Comment by harisibrahimkv** [comment]
Sounds too cheesy to me. Just tagging his handle should be enough.

**Comment by kracekumar** [comment]
I agree with Haris.

On Wed, Nov 25, 2015 at 2:24 PM, Haris Ibrahim K. V. <
notifications@github.com> wrote:

> Sounds too cheesy to me. Just tagging his handle should be enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/212#issuecomment-159537975>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by kirang89** [comment]
I agree with Haris, too.

**Comment by vnbang2003** [comment]
@harisibrahimkv Can you help us with this?

**Comment by vnbang2003** [comment]
Closing it as wontfix
