### ISSUE TITLE
Refactor testing code

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#213]
Refactor testing code
@theskumar @kracekumar i did some random coding with test coverage to increase percentage but i am sure there is lot of place code can be improvised.
As am not very good at py.test Let me know if you have any recommended way to handle duplication of code.

**Comment by theskumar** [comment]
There is nothing fancy about pytest as such. If you like you can still write normal Django tests. That said, there are few advantages of pytest. 

- You can write nomal functions instead creating a class everytime. 
- make use abstracted fixtures like `browser` (See `fixtures.py`) in an easy way. 

There are no rules, just test what need to be tested not more not less. Keep it intuitive for the person reading it thats it.
