### ISSUE TITLE
  Failed building wheel for Pillow

### ISSUE THREAD

**Issue by aniketmaithani** [pythonindia/wye#214]
Though this is not related to `wye` code base in particular. But one of the requirements `Pillow` library gives me this error while I try to install the requirements. 

```   ValueError: --enable-jpeg requested but jpeg not found, aborting.
  
  ----------------------------------------
  Failed building wheel for Pillow
```

Can anybody help me out with this?? 

My system configuration : 
1. Ubuntu-14.04 LTS
Python Version 3.x

**Comment by harisibrahimkv** [comment]
@aniketmaithani IIRC, there are a few system packages that you need to install for jpeg support. Unless you use a certain flag to exclude that feature from Pillow during compilation, it will spit this error out. Didn't the traceback show which package was missing?

**Comment by aniketmaithani** [comment]
@harisibrahimkv 
```ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
```

**Comment by harisibrahimkv** [comment]
@aniketmaithani Try installing `sudo apt-get install libjpeg-dev`and then Pillow again.

**Comment by aniketmaithani** [comment]
@harisibrahimkv thanks. Solved! Closing the issue

**Comment by aniketmaithani** [comment]
Just commenting for future reference : 

This problem can be resolved by firing the following command. 
```
sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk
```

**Comment by SystemDisc** [comment]
Command is now
```
sudo apt-get install libtiff-dev libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl-dev tk-dev python-tk
```

**Comment by bobleujr** [comment]
In case you are using alpine
`apk add tiff-dev jpeg-dev zlib-dev freetype-dev lcms2-dev libwebp-dev tcl-dev tk-dev python2-tkinter`

**Comment by SevaShpun** [comment]
> @aniketmaithani Try installing `sudo apt-get install libjpeg-dev`and then Pillow again.

Thanks!
