### ISSUE TITLE
Workshop details page should be publicly viewable

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#219]
As a non-autneticated user i should be allowed to view the workshop details with all the button deactivated.

**Comment by vnbang2003** [comment]
@curioswati Can you help us with this?

**Comment by curioswati** [comment]
@vnbang2003 , that is a user without logging in should be able to see the details list? But how would I do that? as right now the workshop tab ask for authentication.

**Comment by vnbang2003** [comment]
@curioswati I fixed it . Take a look at commit https://github.com/pythonindia/wye/commit/d2efb8dec3ed429f90857bbd5ec55bedf6c12662
