### ISSUE TITLE
Cannot resolve keyword 'user' into field. Choices are: id, leads, location, location_id

### ISSUE THREAD

**Issue by shankisg** [pythonindia/wye#220]
In workshop views file the get_context_data method in WorkshopList view contain following query below. But the RegionalLead model does have **user** attribute, its should **leads** in the query. 

    regions = RegionalLead.objects.filter(user=self.request.user) 

I will fix this issue and add PR for it.

**Comment by vnbang2003** [comment]
@shankisg Is this bug still open ?

**Comment by vnbang2003** [comment]
Looks like query is fixed  hence resolving it
regions = RegionalLead.objects.filter(leads=self.request.user)

**Comment by shankisg** [comment]
Need to check

**Comment by vnbang2003** [comment]
@shankisg I have fixed it . Once we push to server it will work.
