### ISSUE TITLE
Remainder to Presenter/Requester

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#223]
We need to add cron job to send remainder one week before the workshop day to presenter and requester on the workshop schedule plan. 
By this way it will help presenter and requester to pull back if they have changed the plans or forget to plan things .

**Comment by kracekumar** [comment]
+1.

On Sat, Dec 19, 2015 at 12:55 AM, Vijay <notifications@github.com> wrote:

> We need to add cron job to send remainder one week before the workshop day
> to presenter and requester on the workshop schedule plan.
> By this way it will help presenter and requester to pull back if they have
> changed the plans or forget to plan things .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/223>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by shankisg** [comment]
+1, may be we can use kronos to manage cron jobs.

**Comment by lavish205** [comment]
I want to work on this bug.
For sending reminders can we use celery `crontab` ?

**Comment by vnbang2003** [comment]
@lavish205 Sound good. @kracekumar @vigneshsarma do we have bandwidth for this on server ?

**Comment by vigneshsarma** [comment]
Server shouldn't be an issue here. We are hardly using any CPU. Memory we are using 650M of 1500M.

**Comment by lavish205** [comment]
Cool, I am working on this bug, can anyone please provide me the template of reminder?

**Comment by vnbang2003** [comment]
@lavish205 we don't have template but feel free to create you own for now . we can change later on it.
@harisibrahimkv can you help here with content ?

**Comment by lavish205** [comment]
@vnbang2003 where should I define cronjobs?
I prefer to make `cronjobs.py` file on project root, what do you suggest?

**Comment by kracekumar** [comment]
Django management command is better choice.

On Wed, Mar 30, 2016 at 2:44 PM, Lavish Aggarwal <notifications@github.com>
wrote:

> @vnbang2003 <https://github.com/vnbang2003> where should I define
> cronjobs?
> I prefer to make cronjobs.py file on project root, what do you suggest?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/223#issuecomment-203338353>
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by lavish205** [comment]
@kracekumar can you provide some details how to do it with Django management commands?

**Comment by kracekumar** [comment]
@lavish205 Forget about how to schedule, make sure running the django command will send out emails. https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/

**Comment by vigneshsarma** [comment]
@kracekumar @lavish205 you don't need any management command or special script. once you have setup celery and django correctly celery provides a way to run it. 

Ref: 
- http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#starting-the-scheduler
- http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

**Comment by harisibrahimkv** [comment]
Just a quick note on that. From my experience with celery, I've found cronjobs + django management commands to be more reliable than celery beats / scheduled tasks. Both works, but I've just found the former to be more reliable.

**Comment by harisibrahimkv** [comment]
@lavish205 I think what @kracekumar meant was something like this:

```
from django.core.mail import send_mail

send_mail(
                    message,
                    from,
                    to_list,
                )
```

You'll need to implement the logic of figuring out who all the email should go to (based on dates). This snippet of code will go into some `app/management/commands/task.py` directory. Once you have that tested and running, hook it up to that runs every morning or something and we'll be good to go.

**Comment by harisibrahimkv** [comment]
@vnbang2003 Once @lavish205 Implements this as a celery cron or management command, I will fill in the email content in the appropriate place.

**Comment by harisibrahimkv** [comment]
@lavish205 If you're going with the cronjob model, first implement the management command as I mentioned above and then use `crontab -e` to open up the crontab file and put in something like this:

`*/5 *  *   *   *     cd {project_directory} && {path_to_virtualenv_python} {path_to_manage.py} {your_management_command_name} --settings={path_to_settings_file} >  {path_to_log_file} 2>&1`

**Comment by lavish205** [comment]
I have earlier used django mails and celery, I found  `crontab` very reliable. There is no need to add entry in `crontab -e` celery will manage it.
[crontab](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#crontab-schedules) are easy to implement as well. 
@harisibrahimkv @vnbang2003 @vigneshsarma do let me know which method should I implement.

**Comment by harisibrahimkv** [comment]
@lavish205 Any method is fine really. It is you who came forward to work on the bug and we will respect the decision you make. :)

**Comment by lavish205** [comment]
Do we have to send reminder to all presenter or requester or both?
If requester, then where I can find requester email?

**Comment by vnbang2003** [comment]
@lavish205 Requester  :  IN workshop models requester. user.email .
Where request is Organisation models.

**Comment by lavish205** [comment]
@vnbang2003 getting `AttributeError: 'ManyRelatedManager' object has no attribute 'email'` while using `requeste.user.email`

**Comment by vnbang2003** [comment]
Organisation can have more than one user hence you need to loop for all requester.user.objects.all()
And send email to members of organisation.
Even presenters can be more than one.

**Comment by vnbang2003** [comment]
Pull request : https://github.com/pythonindia/wye/pull/262
Closing it
