### ISSUE TITLE
Tutor able to give a feedback even if it is not related to a workshop

### ISSUE THREAD

**Issue by shubhamgupta2021** [pythonindia/wye#224]
User type tutor is able to see the workshops and also able to see the share feedback button, even if he is not related to that organization.

**Comment by shankisg** [comment]
Yes, we should not show the share feedback button to the users, who are not associated with the workshop.

**Comment by shubhamgupta2021** [comment]
I am working on it.

**Comment by shubhamgupta2021** [comment]
@vnbang2003, Can I mark it fixed?

**Comment by vnbang2003** [comment]
Can we check if build and test coverage is fine then mark as fix.

**Comment by shubhamgupta2021** [comment]
OK cool.

**Comment by shubhamgupta2021** [comment]
@vnbang2003, Can you check the test coveraga and build.

**Comment by shankisg** [comment]
@shubhamgupta2021 any update?

**Comment by shubhamgupta2021** [comment]
@shankisg  My [pull request](https://github.com/pythonindia/wye/pull/227) is already merged. You guys need to check if it is working or not.

**Comment by vnbang2003** [comment]
@shubhamgupta2021 : Can you help us to test on live server . Few completed workshop are
1) https://pythonexpress.in/workshop/14/
2) https://pythonexpress.in/workshop/15/

**Comment by shubhamgupta2021** [comment]
@vnbang2003 @shankisg : I have checked it on the live servers. I am unable to give feedback for these workshops. I can confirm the issue is resolved.

**Comment by shankisg** [comment]
As per test feedback shared by @shubhamgupta2021 closing this issue.
