### ISSUE TITLE
Workshop list should be sorted based on expected date

### ISSUE THREAD

**Issue by shubhamgupta2021** [pythonindia/wye#229]

**Comment by vnbang2003** [comment]
I think it fine to show as they is no harm in showing this.
Is there anything i am missing ?

**Comment by shubhamgupta2021** [comment]
Because of previous workshops, it is difficult to find the new and upcoming workshops

**Comment by shubhamgupta2021** [comment]
Then we have to sort them according to there expected date

**Comment by vnbang2003** [comment]
:+1:

**Comment by shubhamgupta2021** [comment]
should I create a new issue for that?

**Comment by vnbang2003** [comment]
no update this pr itself pls

**Comment by shubhamgupta2021** [comment]
@vnbang2003 , can you test if issue is resolved?

**Comment by vnbang2003** [comment]
it work on my local hence closing it
