### ISSUE TITLE
Fix string formatting issue for __str__ function in workshops/models  

### ISSUE THREAD

**Issue by shankig** [pythonindia/wye#23]
For workshops models the \__str__ function have string formatting issue.

For example \__str__ function for WorkshopLevel model is as below

    def __str__(self):
        return '{}' % (self.name)

To fix this issue we need to use .format, sample below 
   
    def __str__(self):
        return '{}'.format(self.name)

While working on issue #7 , I will fix this.

**Comment by theskumar** [comment]
+1

**Comment by shankig** [comment]
Fixed and merged
commit# 5732162ef0008a3b88ac72d9be89c94dbd6bd4a7
