### ISSUE TITLE
When creating new Regional Lead, not supplying any values throw a "KeyError"

### ISSUE THREAD

**Issue by iAmMrinal0** [pythonindia/wye#230]
There is no check for both parameters existence, "location" and "leads", which results in a Key Error.

**Comment by shankisg** [comment]
@iAmMrinal0 Could please more information to this issue.

**Comment by iAmMrinal0** [comment]
When creating a new Regional Lead if the values for "Location" and "Leads" are not selected, it throws a "KeyError." There is no check to see if they are empty or not. Screenshots:
![2015-12-19-14 32 15_1366x768_scrot](https://cloud.githubusercontent.com/assets/890062/11912329/e3312116-a65d-11e5-8bfb-bb7a3e1fc7ab.png)
![2015-12-19-14 34 34_1366x768_scrot](https://cloud.githubusercontent.com/assets/890062/11912330/e3c15506-a65d-11e5-9020-a45c02efc441.png)

I am working on it.

**Comment by vnbang2003** [comment]
@iAmMrinal0 You mean the error message is not properly displayed ? if yes please go ahead and send pull request.
