### ISSUE TITLE
Unable to move on hold workshop back to requested or active

### ISSUE THREAD

**Issue by shubhamgupta2021** [pythonindia/wye#232]
In the workshop list, if organiser marked any workshop on hold, he can't move that to requested or active state with the Publish/Request button.

**Comment by vnbang2003** [comment]
@shankisg can you please verify it. I have test case it allow me to publish/Request .

**Comment by shubhamgupta2021** [comment]
@vnbang2003, @shankisg I am working on it. I have done all the changes and able to see it in the UI. But when I am testing the same thing using py.test it is not working, it seems that it is using the previous code.

**Comment by shubhamgupta2021** [comment]
@shankisg @vnbang2003 Can you guys verify this fix.

**Comment by vnbang2003** [comment]
Closing it for now.
