### ISSUE TITLE
Workshop once rejected moves to declined

### ISSUE THREAD

**Issue by shubhamgupta2021** [pythonindia/wye#236]
If any workshop is rejected after accepting by a tutor it moves to declined, which can't be accepted by another user.

**Comment by shubhamgupta2021** [comment]
@vnbang2003, @shankisg Is the above behaviour valid?

**Comment by vnbang2003** [comment]
@shubhamgupta2021 I think workshop if rejected by tutor should go to "Requested" status but if Organizer reject it should go to Decline status

**Comment by shubhamgupta2021** [comment]
@vnbang2003, As far as I understood from the code, right now organizer don't have any method to decline the workshop and if tutor reject it, it will go into declined state instead of requested.

**Comment by shubhamgupta2021** [comment]
Sure. I will work on this bug from tomorrow.

**Comment by BeingAnuj** [comment]
@shubhamgupta2021 , I would like to work on this issue .

**Comment by vnbang2003** [comment]
@shubhamgupta2021 Can you confirm @Anuj8826 if you have started work on this.

**Comment by Anuj8826** [comment]
@shubhamgupta2021 actually i just wanted to know your progress on this issue
So if u have done a lot i may take any other issue . I have just joined this project and have been studying it

**Comment by shubhamgupta2021** [comment]
@Anuj8826  you can work on it.

**Comment by shankisg** [comment]
@shubhamgupta2021 & @Anuj8826 could please share update on this issue, it's been long time now.

**Comment by shubhamgupta2021** [comment]
@shankisg: @Anuj8826 wants to work on it, so passed it to him.

**Comment by shubhamgupta2021** [comment]
@Anuj8826, Are you working on this? Please confirm.

**Comment by vnbang2003** [comment]
Looks like @Anuj8826 is busy 
@shubhamgupta2021 if you can help us with this please do.

**Comment by shubhamgupta2021** [comment]
@vnbang2003 Will start working on this from coming weekend.

**Comment by vnbang2003** [comment]
@shubhamgupta2021 Can you please update the status ?

**Comment by shubhamgupta2021** [comment]
@vnbang2003 The code is already got merged. You can check the commit https://github.com/shubhamgupta2021/wye/commit/c5e82138885590fe46e11ea9c41f37bb0a1c2213
