### ISSUE TITLE
Organisations not moved to disabled, even if I am the last user

### ISSUE THREAD

**Issue by shubhamgupta2021** [pythonindia/wye#239]
If I am the only user in an organisation and I delete it, first I see a 404 as I am not redirected to organization list and second in the organisation list I still see the organisation as I doesn't move to deactivated

**Comment by shubhamgupta2021** [comment]
@vnbang2003, please have a look

**Comment by vnbang2003** [comment]
@shubhamgupta2021 What do you want me to look please ?

**Comment by shubhamgupta2021** [comment]
@vnbang2003 Are you able to reproduce that bug in your local environment?

**Comment by vnbang2003** [comment]
I haven't tested code will probably do over weekend. I see you sent a pull request on top of my fix.
Looks like test case doesn't cover this use case. Do you mind to add same  ?

**Comment by vnbang2003** [comment]
@shubhamgupta2021 Found minor bug and have fixed it . Should be working with my next push.
