### ISSUE TITLE
Display day in workshop details page

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/wye#242]
While displaying the date of the workshop like `28, Jan 2015` in detail page https://pythonexpress.in/workshop/12/, display the day like `28, Jan 2015 (Thursday)`. This will be convenient for interested tutor to quickly consider the option.

**Comment by shankisg** [comment]
+1

**Comment by vsham20** [comment]
I am working on this bug.

**Comment by vnbang2003** [comment]
Fixed : https://github.com/pythonindia/wye/commit/dfb705e5b580646bb80d64894aca545a9cbe8610
