### ISSUE TITLE
Admin user is created but unverified

### ISSUE THREAD

**Issue by SudShekhar** [pythonindia/wye#245]
I tried setting up the codebase with the latest code and created the admin user.
However, on trying to login (using admin) I see the email verification required screen.

I was able to login after changing the verified variable to true in the postgres *account_emailaddress* table.

This should be handled by the automatically by the startup script, I think. Any comments?

**Comment by vnbang2003** [comment]
Good point .We need to alter sample_data script to make email verified = True.
https://github.com/pythonindia/wye/blob/master/wye/base/management/commands/sample_data.py
