### ISSUE TITLE
PE logo missing in emails

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/wye#251]
![i](https://cloud.githubusercontent.com/assets/4463796/13028505/f47b0044-d296-11e5-8941-c33d5bfded35.png)

**Comment by vnbang2003** [comment]
@ChillarAnand Where do you see this ?

**Comment by ChillarAnand** [comment]
In all PE mails.

**Comment by vnbang2003** [comment]
Taken care it should work once we push code to server
