### ISSUE TITLE
'Other' in the Org/Tutor location list

### ISSUE THREAD

**Issue by arunta007** [pythonindia/wye#253]
Can we consider adding 'Other' to the Organization/tutor location list?

**Comment by vnbang2003** [comment]
@arunta007 Can you brief a bit more what the use case of others ?

**Comment by arunta007** [comment]
There are situations, for example, Kannur, when there's no value for 'location' that match with where the workshop is to be conducted. In such case, 'other' will come to rescue, no?

**Comment by vnbang2003** [comment]
Yes that will help temporary but for long run we need to allow user to add new location himself.
Can you help us open issue with this feature request to allow user add new location ?
At the same do let me know if you want to add location ?

**Comment by arunta007** [comment]
Sure Vijay. Do you want me to open an issue for letting user add location?
Or we can even try importing all cities in India state-wise, which should
be openly available?

Thanks and regards,

Arunanand T A
http://taa.im

**Comment by arunta007** [comment]
Closing, as a better description of the 'enhancement' is opened at: https://github.com/pythonindia/wye/issues/257
