### ISSUE TITLE
Exception handling not done in Profile details.

### ISSUE THREAD

**Issue by shankisg** [pythonindia/wye#254]
It is suggested to wrap the any **get** models query inside try except block . This line **user_profile = models.Profile.objects.get(user__id=self.request.user.id)** in get_context_data method of ProfileView class is throwing exception in production. 

One more point, why we are comparing user id rather we can compare user objects in Proffile query. Example below

```python
user_profile = models.Profile.objects.get(user=self.request.user)
```
Commit # cba45749767c580b5f1bc3c66c68645e374d5aff

@staranjeet could pls have a look on it.

**Comment by vnbang2003** [comment]
Have converted to function based view and added test error page
