### ISSUE TITLE
Show topic  in workshops page

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/wye#255]
![pe](https://cloud.githubusercontent.com/assets/4463796/13373842/637a97fa-dd98-11e5-91eb-db706f8792cb.png)

It is better to  show topic to  presenter before  he/she accepts the  workshop.

**Comment by vnbang2003** [comment]
Fixed: https://github.com/pythonindia/wye/commit/dfb705e5b580646bb80d64894aca545a9cbe8610
