### ISSUE TITLE
Migrate ClassBased View to Function based View

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#256]
We need to slowly start migrating from ClassBased View to Function based view to have more controls over exception handling.
Priority 
1) Workshop
2) Profile
3) Organisation
4) Others

**Comment by vnbang2003** [comment]
@shankisg Can you help us migrate for workshop section ?
@curioswati Can you help us migrate for organisation module ?
@staranjeet Can you help us migrate for profile module ?

**Comment by curioswati** [comment]
okay @vnbang2003. But currently busy with college stuff. Need some time.

**Comment by shankisg** [comment]
@vnbang2003 that could done. But any specific reason why we are moving away from CBV.

**Comment by vnbang2003** [comment]
To show better error messaging and easier for new comer to start contributing.

**Comment by staranjeet** [comment]
@vnbang2003 : Every view or just the `UserDashboard` view in `profiles` app?

**Comment by shankisg** [comment]
All class based views needs to migrated to functional views

**Comment by vnbang2003** [comment]
Guys,
   Let slowing start migrating  along with other fixes so in next few days we get migrated.

**Comment by vnbang2003** [comment]
Have moved few workshop views.
