### ISSUE TITLE
Add an 'Other' option in the workshop/tutor location and allow to add custom location

### ISSUE THREAD

**Issue by arunta007** [pythonindia/wye#257]
This is an enhanced description of the feature request specified at: https://github.com/pythonindia/wye/issues/253

1. We may allow users to specify their location if that's not available on the dropdown list. This pertains to workshop/tutor location. As of now only a limited set of locations is available in the dropdown. We may provide an 'Other' option, and allow user to enter a custom location.

2. Or instead, we may add as many options as possible to the location dropdown, categorized into States and Cities (or districts), kind of which list should be available openly already.

**Comment by vnbang2003** [comment]
Added FAQ question on how to add location .This should be good for now.

**Comment by vnbang2003** [comment]
@Warlord77 This could be good starting point . Let me know if can work on this.
