### ISSUE TITLE
Allow tutor and Oragniser to view each other contact info

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#267]
Once the workshop is accept we should allow tutor's and orgnisers contact info to be visible once they login . This is easy the bottleneck of getting each other contact info.

**Comment by vnbang2003** [comment]
@curioswati Can you help with quick fix with this. We need this feature for PythonMonth planning.

**Comment by curioswati** [comment]
okay @vnbang2003. but I am not getting exactly what is required..

**Comment by vnbang2003** [comment]
Once the workshop is accepted . We need to display to tutor and requester their contact info so they can speak to each other.
Note: This should be only visible to Requester and tutor only.

Let me know if it is clear.

**Comment by curioswati** [comment]
Sorry but I am unable to understand the flow. I don't have much knowledge of the workshop module. So if you could elaborate please.
These are few questions:
Which page exactly do I need to work on?
What test orgs I will need to create if I have to understand, like for now I create a college as an org to test things. So will it suffice or do I need to create another user/orgs? like the terms tutor/orgs/requester are confusing a bit.
I am not able to connect the dots.

**Comment by vnbang2003** [comment]
Once you have organization created. You can request for workshop.
Once workshop is created tutors can accept the workshop.

In workshop detail page (https://pythonexpress.in/workshop/9/) . HTML file: workshop/details.html.
We need to check condition if logged in person is presenter or requester 
In workshop model requester means organisation hence we need to check organization members name against logged in person.
Presenter is list of user (There can be more than one speaker).

Workshop models fields :
 requester = models.ForeignKey(
        Organisation, related_name='workshop_requester')
 presenter = models.ManyToManyField(User, related_name='workshop_presenter')

Is that more clear ?

**Comment by vnbang2003** [comment]
@curioswati at the same in next pull request add you name in contributors list 
https://github.com/pythonindia/wye/blob/master/CONTRIBUTORS.txt

**Comment by curioswati** [comment]
okay just double checking..
> Once workshop is created tutors can accept the workshop.

Tutors are the users of the organisation, right?

> We need to check condition if logged in person is presenter or requester

Presenter and requester are on the same side. Requester is the organisation and presenters are the members of the organisation who have accepted the workshop i.e. tutors, right?

So for this task, I have three conclusions:
* if the logged in member is a member of the organisation and they are not the tutor/presenter then the contact info of the presenters should be displayed to them.
* If the logged in member is tutor/presenter then the contact details of the all other members should be displayed.

OR
On a workshop details page, all member's details should be visible to the logged in user if the user is the member of the requesting organisation.

OR
On the detail page, the tutors contact details should be visible to everyone who login even if they are not a member of the requesting organisation.

**Comment by vnbang2003** [comment]
@curioswati is it possible to get this feature to the earliest as am having tough time to keep writing intro emails

**Comment by curioswati** [comment]
@vnbang2003, my laptop is not with me for the last week, as it had some issue. Expecting it back in 2-3 days. Then only i will be able to fix the issue.

-----Original Message-----

**Comment by vnbang2003** [comment]
@curioswati If i find time will fix else pls do help over weekend with fix.

**Comment by vnbang2003** [comment]
Fixed it.
