### ISSUE TITLE
Twitter update for workshop accepted

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#268]
Presently when workshop is requested we automatically update twitter handler to display workshop request details. We should add functionality to display update once workshop is requested.

**Comment by vnbang2003** [comment]
@harisibrahimkv Can you help with this ?

**Comment by harisibrahimkv** [comment]
@vnbang2003 Yep, can can. Will need some time though. Dealing with a laptop
crisis.

On 31 May 2016 at 12:02, Vijay <notifications@github.com> wrote:

> @harisibrahimkv <https://github.com/harisibrahimkv> Can you help with
> this ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pythonindia/wye/issues/268#issuecomment-222603220>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AArzPJxrzBIjqbb5H19CYtNkFdR9r8-Jks5qG9XggaJpZM4IOF03>
> .
>



-- 
Haris Ibrahim K. V.
http://sosaysharis.wordpress.com
@harisibrahimkv <http://twitter.com/harisibrahimkv>

**Comment by vnbang2003** [comment]
@harisibrahimkv No Problem .

**Comment by vnbang2003** [comment]
Looks duplicate hence closing it. #212
