### ISSUE TITLE
Write Script which will automatically send email to regional mailing list on workshop request

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#269]
Presently when new workshop is request , Someone has to manually drop email to malign list requesting for tutor.
We should plan to write script when will send email to mailing list automatically.
Example: If workshop is requested for bangalore location it should send email to bangpyper.
If workshop is requested for Ncr location it should send email to Ncr-python

**Comment by sourabhtk37** [comment]
Will try to implement. @vnbang2003

**Comment by vnbang2003** [comment]
@sourabhtk37 Any update on this ?

**Comment by sourabhtk37** [comment]
I am still stuck with location thing,still in learning phase na that's why. But trying my level best.

**Comment by vnbang2003** [comment]
This is taken care with latest fix.
