### ISSUE TITLE
twitter update broken

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#282]
Looks like the recent changes have broken twitter update url:
https://twitter.com/pythonexpress/status/757674752370626561

@harisibrahimkv Can you help with this ?

**Comment by vnbang2003** [comment]
@harisibrahimkv do you have time to help us with this ?

**Comment by juggernaut451** [comment]
@vnbang2003 is this bug fixed?

**Comment by harisibrahimkv** [comment]
@juggernaut451 Apparently not. I was planning to work on it, but just didn't get the time. Could you give me until the end of this weekend to take a stab at it? If I can't do it by then, feel free to fix it.

Thanks!

**Comment by vnbang2003** [comment]
@juggernaut451 by the time you can pick other bug to work on.

**Comment by harisibrahimkv** [comment]
This doesn't seem to be happening now. I am not sure how that one instance happened.

https://twitter.com/the_test_bold/status/762227075683979264

@vnbang2003 Did you spot any other instances of this happening?

**Comment by vnbang2003** [comment]
@harisibrahimkv That because we have hard coded for now.
https://github.com/pythonindia/wye/commit/69e6bdc31b073470658808ccb9d6124150fcbbd8

**Comment by harisibrahimkv** [comment]
@vnbang2003 Thanks. Fixed it: https://github.com/pythonindia/wye/pull/312
