### ISSUE TITLE
Display location with combination of name and state

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#284]
There are good chances to have duplicate location name across states hence it will good to display location as combination of name and state's name

**Comment by vnbang2003** [comment]
@ultimatecoder @TroJan @stalwart201 Can one of you help with this ?

**Comment by realslimshanky** [comment]
@vnbang2003 would like to help.

**Comment by vnbang2003** [comment]
@realslimshanky sure. Let me know if you need any help

**Comment by realslimshanky** [comment]
@vnbang2003 you want just the "interested locations" with this modification or "location" too ?

**Comment by vnbang2003** [comment]
@realslimshanky there are few page we display location 
1) Profile(Both interested location and location)
2) Organisation
3) Workshop
4) https://pythonexpress.in/workshops_upcoming/


We need to change or add property for location to send us concatenated location name.

**Comment by vnbang2003** [comment]
@realslimshanky Are you working on it ?
