### ISSUE TITLE
Add blog option

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/wye#288]
Suggestions

- [pelican](http://blog.getpelican.com/)
- [pelican-admin](https://github.com/fjcaetano/pelican_admin)
- [zinnia](http://django-blog-zinnia.com/)

Please feel free to add other appealing packages.

**Comment by ChillarAnand** [comment]
- [lektor](https://github.com/lektor/lektor) has good admin like django.
- [nikola](https://github.com/getnikola/nikola/)

**Comment by aniketmaithani** [comment]
my two cents on Nikola

**Comment by vnbang2003** [comment]
I think we use pelican for PyCon India  and Bangpypers let use same to avoid too many things .

**Comment by kracekumar** [comment]
Pelican is one of the choices, and the `Lektor` looks stellar. I am ok with any of those. The question is should we maintain the blog in this repo or different repo?

**Comment by vnbang2003** [comment]
If it doesn't mess existing blog and urls am fine to use it , less thing to manage.

**Comment by kracekumar** [comment]
My vote is for new repo.

**Comment by vnbang2003** [comment]
Let create new repo .

**Comment by kracekumar** [comment]
Blog is at here https://github.com/pythonindia/wye-blog
