### ISSUE TITLE
Worskshop life Cycle

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#29]
Each workshop request needs to go through below state
1) requested(when new request is done)
2) accepted(when user/tutor accept it)
3) declined(if not resource available)
4) completed(Feedback is shared hence we say it completed)

**Comment by theskumar** [comment]
I think we can also add `draft` status.

**Comment by vnbang2003** [comment]
Have added Workshop status constant in wye/base/constants.py.

**Comment by vnbang2003** [comment]
Closing it as we have defined workflow status.
