### ISSUE TITLE
`Workshop status - Assigned` email getting sent to a whole lot of people.

### ISSUE THREAD

**Issue by harisibrahimkv** [pythonindia/wye#293]
The following email is being sent to a bunch of people. Why is that? There should be an option to opt out of these notifications.

Also, even if it is being sent, it should be to individual people rather than exposing everyone's email ids.

__Subject__:
`Workshop status - Assigned`

__Body__:
`Hello folks! Just giving you a heads up. The Workshop you are planning to conduct on Aug. 13, 2016 has been assigned to sushrut. Please visit the url below for more information. http://pythonexpress.in/workshop/53/ Warmly, The PythonExpress team.`

**Comment by vnbang2003** [comment]
We already have ticket and working on fix. #283  hence closing it as duplicate

**Comment by vnbang2003** [comment]
Sorry mis understood. Yep we need to find way to add notification  flag in profile

**Comment by vnbang2003** [comment]
@curioswati Can you help with this ?

**Comment by curioswati** [comment]
@vnbang2003, I can once I have my laptop back. Probably 2-3 days.

Regards,
Swati Jaiswal

-----Original Message-----

**Comment by vnbang2003** [comment]
@curioswati that not a problem

**Comment by ankur0493** [comment]
@vnbang2003 This is not actually just an enhancement. I think there is some bug or something. I started receiving updates about workshops at GGSIPU though I was neither the requester nor the speaker.

**Comment by harisibrahimkv** [comment]
@vnbang2003 This is not just about the notification flag. Some random workshop assignment is getting sent to a random bunch of people with all addresses in the `to` list. The questions are:

1. Why are all those people getting this email? I am not presenting, requesting or organizing this workshop.
2. Why are all the email ids in the `to` list? They should be either sent individually or on `bcc` at least.
3. Notification flag as well.

**Comment by ankur0493** [comment]
#283 is an open issue for 1 and 2

**Comment by harisibrahimkv** [comment]
Ah I see. Thanks @ankur0493.

**Comment by curioswati** [comment]
hey @vnbang2003 , Is there any work required here?

**Comment by vnbang2003** [comment]
I think ankur's fix will do
