### ISSUE TITLE
Unable to register as a volunteer for an accepted workshop

### ISSUE THREAD

**Issue by vishnutalanki** [pythonindia/wye#294]
I want to volunteer for an accepted Python3 workshop on Aug 13 at RNSIT, Bangalore.
Not as a tutor, but a volunteer to help the tutor. Is this option available?.
Thank You.

**Comment by vnbang2003** [comment]
@vishnutalanki Presently we don't have this feature but we will consider in near feature to get this.

**Comment by vnbang2003** [comment]
Closing this issue as we have #304  work in progress to address this.
