### ISSUE TITLE
Add report tab to display few status and info(Visible only to Admin)

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#297]
1) Add page to display all organization which has not requested for workshop yet
2) Workshop declined

**Comment by ankur0493** [comment]
Hi, I can start working on this. Please assign it to me.

**Comment by vnbang2003** [comment]
@ankur0493 please start working on it . If possible can you first help with existing bugs as this feature is for v1.0 and i need add more .

**Comment by ankur0493** [comment]
Sure I can.. But I see a lot of issues are already taken up by someone. Can
you please point out a bug that needs to be addressed soon and is
unassigned? I'll start working on it...

**Comment by vnbang2003** [comment]
How about #292 It's a new feature. ?
