### ISSUE TITLE
Integrate django-allauth for authentication

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#3]
We need to integrate django-allauth for  social account authentication.

**Comment by DESHRAJ** [comment]
Hey @vnbang2003 I am interested in working on this.

**Comment by vnbang2003** [comment]
@DESHRAJ Sure.

**Comment by vnbang2003** [comment]
@DESHRAJ  Are you working on it ?

**Comment by DESHRAJ** [comment]
Yes, I have integrated django allauth and its templates but designing needs to be done over the templates.

**Comment by vnbang2003** [comment]
Cool Thanks. Hope to see you pull request soon.
Am assigning it to you.

**Comment by vnbang2003** [comment]
@DESHRAJ I have merged code as initial configuration checkin. But we need to get social login and normal login work to close this issue. Do Let you know if you can fix them ?

**Comment by DESHRAJ** [comment]
Ok sure. I can add the social login. :)

**Comment by vnbang2003** [comment]
Close this as basic integration is done. Next steps are worked in #33
