### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#30]
Blog post about monthly workshops or any specific workshop should be posted. 
In mailing list this library was recommended 
https://github.com/Fantomas42/django-blog-zinnia

**Comment by staranjeet** [comment]
I can work on this issue. But I will need some more information about how and what to do. 
@vnbang2003

**Comment by vnbang2003** [comment]
@staranjeet We need to integrate this library and make a document how to use it .
We will be having many blog to be written for this product.

**Comment by staranjeet** [comment]
Ok. I am working on this. I will initially present a draft of how to integrate the blogging app into `wye`.

**Comment by staranjeet** [comment]
This got a bit late as I was a little busy. The installation of zinnia blog is very easy. Docs are a good starting point. I have integrated in my [branch](https://github.com/staranjeet/wye/tree/zinnia-blog-integration). Most of the part lies in customizing the look and feel of the blog. For that we need to edit `zinnia/base.html` which will involve mainly the css and a bit of html. Also it has a very nice admin where there can be moderators of the post and comments as well. For each post published a mail will be sent to the moderators.

Such things can be discussed more clearly once we have the basic installation done. 
As a suggestion, we should customize the Django admin and change its look also.

![selection_001](https://cloud.githubusercontent.com/assets/4302268/10658025/7f035fae-78b0-11e5-98e4-51b5b2e42ccf.png)
![selection_002](https://cloud.githubusercontent.com/assets/4302268/10658030/8c7dbea4-78b0-11e5-9a2c-deae2e9e0470.png)
![selection_003](https://cloud.githubusercontent.com/assets/4302268/10658034/926637ec-78b0-11e5-918c-aa7805a4e530.png)

**Comment by vnbang2003** [comment]
Looks good. @kracekumar @harisibrahimkv  Any inputs ?

**Comment by kracekumar** [comment]
We can't allow users to use Django Admin to create a blog post. I will
provide more details tomorrow.

On Thu, Oct 22, 2015 at 12:29 PM, Vijay <notifications@github.com> wrote:

> Looks good. @kracekumar <https://github.com/kracekumar> @harisibrahimkv
> <https://github.com/harisibrahimkv> Any inputs ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/30#issuecomment-150125360>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by kracekumar** [comment]
@harisibrahimkv Auto deploy on non full time projects are tricky. Deployed code can cause `Internal Server Error`, so it is advised to deploy the code when someone is around to revert back.

**Comment by kracekumar** [comment]
@staranjeet has covered most of the parts. One required feature is to allow `tutors/admin` to post and reviewed by moderators (Zinnia has moderators concept).

**Comment by vnbang2003** [comment]
@staranjeet Can you help answer @kracekumar query so we can plan this for v0.2 ?

**Comment by staranjeet** [comment]
Ok I will have a look at his query and get back regarding this soon.
