### ISSUE TITLE
Workfow for Volunteer to support workshop tutor

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#304]

**Comment by shankisg** [comment]
@vnbang2003 any plan on this.

**Comment by vnbang2003** [comment]
I think its dependent on issue : #302 .
Plan here is to get workflow where user can register them self as volunteer for workshop (2-3 user max) . Role of Volunteer is support to students along with tutor.

**Comment by shankisg** [comment]
Proposed plan this ticket/issue:

- Add new role as **Volunteer**
- When to ask for number of Volunteers required
    - When tutor accepts a workshop, it should display a popup asking for number of Volunteer required. Number should be a dropdown, range from 1-10 or 1-5 . (+1 for me) .
    - Or, Ask this to requester for number of Volunteer required, while adding workshop.

- Display **accept as Volunteer**:
    - Display accept button in workshop listing page
    - Display accept button in workshop details page

Edge case : Display **accept as Volunteer** to user with role as Volunteer. Do not display accept as Volunteer  to tutor.

**Comment by vnbang2003** [comment]
@shankisg To start with sound good. Let create new branch called dev and workshop this so we can continue to hot patch to master branch directly.

**Comment by shankisg** [comment]
@vnbang2003 , Ok.

To start with, tutor would be asked for number Volunteer required while accepting workshop.

**Comment by vnbang2003** [comment]
@shankisg Any update on this ?

**Comment by shankisg** [comment]
@vnbang2003 planning to ad PR by this week.

**Comment by vnbang2003** [comment]
@shankisg We are getting some help with UX. If you can send pull request asap we can ask our UX expert to take a look and help with design.

**Comment by vnbang2003** [comment]
@shankisg  I have merged the code with new branch:
Couple of Point
1) opt out as volunteer button  was not working on safari browser
2)Once I opt as volunteer we need to display full name, email id and Mobile number only to tutor.
3) Test Case to support it.

**Comment by shankisg** [comment]
Ok

**Comment by vnbang2003** [comment]
@shankisg  I merged code with development branch . Can you please help test once again so i can plan to push to prod once you give 👍

**Comment by shankisg** [comment]
@vnbang2003 Will check and let you know.

**Comment by shankisg** [comment]
@vnbang2003 tested volunteer flow, looks good to me

**Comment by vnbang2003** [comment]
Code is checked in hence closing this issue.
@shankisg  Thanks for helping.
