### ISSUE TITLE
Workshop list page should link to workshop detail pages

### ISSUE THREAD

**Issue by ankur0493** [pythonindia/wye#313]
The `/workshop/` page currently lists all the upcoming workshops in locations that the user has indicated he'll be able to deliver a workshop in, but it doesn't links to the workshop.

**Comment by vnbang2003** [comment]
@ankur0493 what do you mean by "but it doesn't links to the workshop" ?

**Comment by kracekumar** [comment]
What he refers is table entry doesn't have a hyperlink to workshop detail page.

**Comment by ankur0493** [comment]
@kracekumar right. Just like `/workshops_upcoming` page has hyperlinks to the details pages.

**Comment by ankur0493** [comment]
Seems the row is clickable only for regional leads, organizers, and admins (is_not_tutor is True for these):

`{% if is_not_tutor %}
   <tr class="clickable-row" data-href="{% url 'workshops:workshop_detail' workshop.pk %}">
{% else %}
  <tr>
{% endif %}`

Why so?

**Comment by vnbang2003** [comment]
@ankur0493 I don't recall exact reason to add this condition but looks we don't need that condition.
