### ISSUE TITLE
Tutor Should be Able to Contact the Requester

### ISSUE THREAD

**Issue by ankur0493** [pythonindia/wye#314]
There seems to be no way for a tutor to contact the requester.. Direct contact details of the requester should be shared as soon as one accepts a workshop. Also, people should be able to comment on the workshops if they need any clarification.

**Comment by vnbang2003** [comment]
This feature is live now hence marking it's a not a bug

**Comment by ankur0493** [comment]
I still do not see an option to contact the college for one of the workshops I accepted. 'College Representative' field is blank. If you were referring to that field when you said that the 'feature is live', then maybe this field needs to be made mandatory.

**Comment by vnbang2003** [comment]
Yep looks like display bug needs to be fixed.
