### ISSUE TITLE
Sign in via github is not working

### ISSUE THREAD

**Issue by Warlord77** [pythonindia/wye#317]
It authenticates with github but gives error like this.
![screenshot from 2016-08-08 13-55-30](https://cloud.githubusercontent.com/assets/16765365/17473781/fb33d97e-5d6f-11e6-98c5-92e41c9380bb.png)

**Comment by theskumar** [comment]
@vnbang2003 would it possible for you check if you got something in the email?

**Comment by abhi9898** [comment]
Checked it, there is no its working fine!

**Comment by theskumar** [comment]
Thanks as we are not getting any other complains I'm closing this now
