### ISSUE TITLE
Date filters on the workshop listing page.

### ISSUE THREAD

**Issue by harisibrahimkv** [pythonindia/wye#318]
Implement filters on the workshop listing page to filter by dates, topics, location, trainer, etc.

* This came up when we decided to pull up each week's workshops for preparing blog posts on them.

**Comment by vnbang2003** [comment]
@ankur0493 Would you like to work on it ?

**Comment by ankur0493** [comment]
With a long weekend coming up, I guess I can.

Regards,
Ankur Gupta

**Comment by ankur0493** [comment]
Working on it.. Should be able to checkin by late evening today..
