### ISSUE TITLE
In tweets, try including workshop city if not complete addr is not possible. 

### ISSUE THREAD

**Issue by theskumar** [pythonindia/wye#327]
Currently, the organization (containing name + address) detail is completely omitted if char length > 140, we should be able to optimize further with just including the city of organization and check if that fits within 140 char.

https://github.com/pythonindia/wye/blob/master/wye/workshops/models.py#L205-L209

@harisibrahimkv @vnbang2003  thoughts?

**Comment by harisibrahimkv** [comment]
@theskumar Valid point. Doesn't hurt anyone to try that. Have pushed a fix.

**Comment by theskumar** [comment]
Looks great, thanks :)

**Comment by harisibrahimkv** [comment]
@theskumar Doesn't seem to be merged though: https://github.com/pythonindia/wye/pull/328

**Comment by theskumar** [comment]
@harisibrahimkv ah my bad. @vnbang2003 can you look into this please. It seems i don't have merge access, so can't help it here.

**Comment by theskumar** [comment]
Well, found the merge button :D
