### ISSUE TITLE
Integrate Social login using django-allauth

### ISSUE THREAD

**Issue by DESHRAJ** [pythonindia/wye#33]
This includes integrating the social authentication using following providers: 

a) Google
b) Twitter
c) Github

**Comment by DESHRAJ** [comment]
@vnbang2003, Please assign it me. :)

**Comment by vnbang2003** [comment]
Done

**Comment by DESHRAJ** [comment]
@vnbang2003 , I think this issue is resolved and now it can be closed. If anything else need to be done on this issue, then please let me know.

**Comment by vnbang2003** [comment]
@DESHRAJ Can we display logo instead of Text? Reference https://in.pycon.org/cfp/accounts/login/?next=/cfp/

**Comment by DESHRAJ** [comment]
Hey @vnbang2003 , exams are going in my college. I will do this next week. :)

**Comment by mascot6699** [comment]
I get `SocialApp matching query does not exist.` googling for the error says the app_id and secrets needs to generated. I guess you did not put them in database.py as they need to be secret. but for development /testing purpose can you illustrate the process of getting them in readme or point to docs or circulate among collaborators via email? Just a suggestion.

**Comment by vnbang2003** [comment]
@mascot6699 you need to generate own secret key for local development.
You can read details here : http://django-allauth.readthedocs.org/en/latest/

**Comment by vnbang2003** [comment]
@DESHRAJ We need to get beta verison live by Nov 1st. Can we get this issue close asap ?

**Comment by vnbang2003** [comment]
Just saw @Praseetha-KR  has fixed it. Hence closing it.
