### ISSUE TITLE
Under Workshops, Github Link not working

### ISSUE THREAD

**Issue by GeekyShiva** [pythonindia/wye#330]
Under workshop section the reference to github link is not working for any workshop mentions on the website -
![github](https://cloud.githubusercontent.com/assets/14253823/17832147/a3431f14-6719-11e6-8b3e-0a1c97d53350.jpg)

[https://pythonexpress.in/workshops_info/](url)

**Comment by abhi9898** [comment]
What is was supposed to do then ?

**Comment by vnbang2003** [comment]
It simple we need to link to material so people can use it as foundation.
We need to find material from tutors.

**Comment by RishabhJain2018** [comment]
@vnbang2003 Can I work on this issue?

**Comment by GeekyShiva** [comment]
please fix this issue because this not letting us use  the tutorials

**Comment by vnbang2003** [comment]
@RishabhJain2018 Pls go ahead

**Comment by RishabhJain2018** [comment]
@vnbang2003 Who are the current tutors so that I can find the material from them?

**Comment by vnbang2003** [comment]
@RishabhJain2018 I need to reach our to tutor and ask permission before we add it here.
Give me couple of days will update here once i listen from tutors

**Comment by theparadoxer02** [comment]
is it just going to add the link to the material,or should we have to create it ?
Also what will be taught in that material django or what ?

**Comment by RishabhJain2018** [comment]
@vnbang2003 sure. :smile:

**Comment by vnbang2003** [comment]
@RishabhJain2018 Few link are here: https://github.com/pythonindia/wye/wiki/Resources
