### ISSUE TITLE
Reduce timespan of 2 week to organize workshop for convenience

### ISSUE THREAD

**Issue by surajnarwade** [pythonindia/wye#335]
we want to organize workshop on 10th September but its giving us error of "Workshop request has to future dates at least 2 weeks from today". Please look into it.

Thanks & Regards,
Suraj Narwade

**Comment by vnbang2003** [comment]
We need 15 days to find volunteer and plan for logistics hence looks logic is fine.
If we need to customize date we can reachout to admin team and get dates changed.
