### ISSUE TITLE
Profile Edit button unresponsive on workshop details page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [pythonindia/wye#342]
Hi,

Clicking on edit profile button gives Page not found.

Regards,
Mehul

**Comment by RishabhJain2018** [comment]
@kracekumar @ChillarAnand @vnbang2003 Can I work on this issue?

**Comment by vnbang2003** [comment]
@RishabhJain2018 Are you working on it ? Any ETA ?

**Comment by vnbang2003** [comment]
@mehul-m-prajapati Can you elaborate more as i see edit button work for us.

**Comment by mehul-m-prajapati** [comment]
Hi,

I am using Chrome Version 53.0.2785.143 m

1. Logging into account
2. Clicking on Profile.
3. Clicking on Edit button
![capture](https://cloud.githubusercontent.com/assets/7879392/19230599/0c4b6efc-8ef3-11e6-8b3e-aefa93345d16.PNG)

![capture1](https://cloud.githubusercontent.com/assets/7879392/19230609/1ac06032-8ef3-11e6-945a-7879d11bfdc8.PNG)

**Comment by vnbang2003** [comment]
@Praseetha-KR Can you help us with this ?

**Comment by vnbang2003** [comment]
Closing it as won't fix as its a rare case.
