### ISSUE TITLE
Add link to blog.pythonexpress.in

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#344]
http://blog.pythonexpress.in/posts/

**Comment by vnbang2003** [comment]
@Praseetha-KR  Can you help us design this change in home page ?

**Comment by theparadoxer02** [comment]
@vnbang2003 i would like to help

**Comment by vnbang2003** [comment]
@theparadoxer02 Please go ahead. Just share plan here only how you want to implement it.

**Comment by theparadoxer02** [comment]
we can add a new link named 'Blog' beside/between the 'Contact Us' and 'Login' button in header and can redirect to http://blog.pythonexpress.in

**Comment by vnbang2003** [comment]
I was thinking to add section in home page and display blogs from this link :http://blog.pythonexpress.in/posts/

Too many tab will look ugly.

**Comment by theparadoxer02** [comment]
so what are you planning to do ?

**Comment by vnbang2003** [comment]
I think add a tab with twitter feed and blog section would be better. Similar to one we have for PyCon India website's what happening section: https://in.pycon.org/2016/

**Comment by vnbang2003** [comment]
FIXED: https://github.com/pythonindia/wye/pull/380
