### ISSUE TITLE
Emails html has no formatting

### ISSUE THREAD

**Issue by akarambir** [pythonindia/wye#347]
Emails being sent regarding workshops are not properly formatted html emails. I didn't find any existing issue regarding this; so filing this one. Example:

<img width="565" alt="screen shot 2016-09-13 at 3 36 51 pm" src="https://cloud.githubusercontent.com/assets/653561/18470010/31d2590a-79c8-11e6-88d9-217a555f43d2.png">
 I would like to work on this one as a start. Then maybe help with #283

**Comment by aditya-konarde** [comment]
Hello,
I would like to work on this as my first contribution. Could you please tell me where I can start? :)

**Comment by vnbang2003** [comment]
@aditya-konarde I think you need to look at send_email function and check if we pass both html and txt content that would fix the issue.

**Comment by vnbang2003** [comment]
With Latest change with email template, we have fixed hence closing it.
Do reopen if find again email broken.
