### ISSUE TITLE
Display tutor's info in workshop details page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#354]
In the workshop details page we display college and tutor contact info.
We have been getting lot of request from college to display tutor's info like location, linkedin, github link .

**Comment by curioswati** [comment]
I am working on it.
Just want UI suggestions.
should I add the links next to the name in the same line and show each name on a new line?

like this:

![screenshot from 2016-10-02 20 46 16](https://cloud.githubusercontent.com/assets/8040201/19021527/4eb6a2ec-88e1-11e6-9dfa-7b83f9a4d288.png)

**Comment by vnbang2003** [comment]
Let's link with each name user profile link .
Just curious how do you plan to display info using profile page ?

**Comment by curioswati** [comment]
> Let's link with each name user profile link 

That is, on clicking user's name, we should redirect to profile page?

> Just curious how do you plan to display info using profile page ?

I was using the workshop.presenter.profile to get the details. inspired from a model method in workshop models named `get_presenter_list`.

**Comment by curioswati** [comment]
@vnbang2003 will any test be required here?

**Comment by vnbang2003** [comment]
@curioswati Yes If we have backend changes.

**Comment by vnbang2003** [comment]
@curioswati Can you make UI changes for it asap so we can have @Praseetha-KR  look and share her inputs from UX point of view.
