### ISSUE TITLE
When we login with local credtinals it throws error.

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#36]
Once we entered login details it throwing below error.

AttributeError at /accounts/login/

'tuple' object has no attribute 'encode'

Request Method: 	POST
Request URL: 	http://localhost:8000/accounts/login/
Django Version: 	1.8.5
Exception Type: 	AttributeError
Exception Value: 	

'tuple' object has no attribute 'encode'

Exception Location: 	/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/smtplib.py in login, line 641

**Comment by vnbang2003** [comment]
@DESHRAJ Can you look in to this. Once i added email details it throwing error.

**Comment by DESHRAJ** [comment]
I think there is some error with smtp. Can you try setting the EMAIL_BACKEND to console using the following line:
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

Hope this helps.

**Comment by vnbang2003** [comment]
@DESHRAJ  If this is fixed can you close the ticket ?

**Comment by DESHRAJ** [comment]
Yes this issue is fixed now. I think I dont have rights to close the issue. So, @vnbang2003 can you do it for me ?
