### ISSUE TITLE
Change the UserType To Enum Kind Of declarations. Remove the hard coding slug values.

### ISSUE THREAD

**Issue by seenureddy** [pythonindia/wye#366]
I'm suggesting Enum kind of declaration is the best way to remove the hard coding values in UseType model. Check the following links: 
1) https://www.quora.com/What-is-the-best-way-to-implement-enums-in-Python
2) http://stackoverflow.com/questions/36932/how-can-i-represent-an-enum-in-python

I have followed this style in one of my projects. This is for Python2.7.

Class Type:
        A,B,C = range(1,3)

Class A:
         TYPE_CHOICES = ((Type.A, "A"), (Type.B, "B"), (Type.C, "C" ))
         slug = models.PositiveSmallIntegerField(choices=TYPE_CHOICES)

**Comment by vnbang2003** [comment]
it was by choice we wanted to make it DB table. hence marking it as wontfix.
