### ISSUE TITLE
Add Facebook link in footer

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#367]
Add Facebook page link in footer : https://www.facebook.com/PythonExpressdotin/

**Comment by sourabhtk37** [comment]
ON it.
Acha and can we use label hacktoberfest to attract more developers to work on issues?
(Just a suggestion :+1: )

**Comment by sourabhtk37** [comment]
To be frank I can't find the html file(footer) where I need to put the fb link.There are so many HTML files.

**Comment by vnbang2003** [comment]
@sourabhtk37 its in settings.py i guess
