### ISSUE TITLE
Adding new topic on Raspberry-Pi

### ISSUE THREAD

**Issue by mehul-m-prajapati** [pythonindia/wye#375]
Hi,

IoT is booming now a days and R-Pi provides IoT support.

We can run python and by installing its libraries, we can also control some hardware like GPIO. 

Simple projects like line follower robot can be made using Python and R-Pi.

I believe, we should add this **topic:** R-Pi with Python

**Comment by vnbang2003** [comment]
Couple things before we add
1) How many tutor can help us with this
2) Topic (https://pythonexpress.in/workshops_info/)
3) Material example for reference.

**Comment by mehul-m-prajapati** [comment]
1) How many tutor can help us with this
-I am the one. May be we need to find some new tutors for this

2) Material example for reference.
-We can add basic porting of Ubuntu file-system, running python, using python libs for H/W handling etc.

I am currently working to make reference materials.

**Comment by vnbang2003** [comment]
Excellent . Let get reference material so we an start moving on this.
