### ISSUE TITLE
Tutor - Update Profile - Issues on Interested sections & Interested State

### ISSUE THREAD

**Issue by sivaa** [pythonindia/wye#388]
The previously saved values of "Interested Sections" and "Interested State" should be highlighted whenever "Update Profile" screen is opened.

**Comment by vnbang2003** [comment]
@sivaa I don't see this bug . Can you check again ?

**Comment by sivaa** [comment]
"Interested Sections" field is working now. But, "Interested State" is still not highlighting my selections.
