### ISSUE TITLE
Enable travis to run on this project

### ISSUE THREAD

**Issue by theskumar** [pythonindia/wye#39]
@vnbang2003 can you please enable travis for this project, so the failing test are visible during PR. Also, it would be nice we can encourage people to write test for the features they are submitting. It really become a pain point to write test later in the development cycle.

**Comment by kracekumar** [comment]
+100.

**Comment by vnbang2003** [comment]
@theskumar For test case +1 . 
For Travis i think its too early let gets project to some shape and enable it.

**Comment by mascot6699** [comment]
@theskumar @vnbang2003 Please tag me when we enable travis I really want to learn how its done. Thanks in advance.

**Comment by vnbang2003** [comment]
@theskumar We are in very good shape . Would you like to take and close it.

**Comment by theskumar** [comment]
Sure, will do.

**Comment by theskumar** [comment]
Things look good. I'm closing this up.
