### ISSUE TITLE
Tutor Share Feedback fails with error message.

### ISSUE THREAD

**Issue by PabitraPati** [pythonindia/wye#390]
1. Login as Tutor.
2. Go to workshop page. For any workshop conducted, you will be shown share Feedback link.
3. Click on the link and fill the required details. Click the 'Submit' button

Observation :
 - Currently, clicking on the 'Submit' button, says - "something went wrong. Mail sent to webmaster." (Attached the screenshot for the same). 
 - In the top right corner, Login and Sign up buttons are shown, even though tutor is logged in. But, clicking on the login button, takes user to Dashboard page, instead of asking for login credential.
 - Again, navigating back to workshop page, 'Share Feedback' button is not present anymore. And this shows tutor as logged in again, which is confusing, whether the feedback was shared or not?

Requirements :
 - Error message should not be shown to tutor on sharing feedback and the same should be posted successfully.
 - No Login or Sign Up button should be shown in the resulting page when user clicks on the Submit button for the feedback.
 - In case any error during feedback sharing, tutor should be shown the 'Share Feedback' button in workshop page back again.
![wye_share_feedback](https://cloud.githubusercontent.com/assets/8273486/20869753/5fb5423e-ba9f-11e6-8f51-9fb3c3264242.png)

**Comment by vnbang2003** [comment]
@shankisg Can you help with this ?
