### ISSUE TITLE
Testing Layout

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#40]
We need to enable testing layout for this project.
Plan is to use pytest

**Comment by vnbang2003** [comment]
@theskumar Can you help with this?

**Comment by vnbang2003** [comment]
@theskumar are you on it ?
@kracekumar Can you also help on it?

**Comment by theskumar** [comment]
@vnbang2003 i'll take a stab today.

**Comment by vnbang2003** [comment]
@theskumar  Assigning to you as you are working on it.
