### ISSUE TITLE
ModelAdmin class for each model

### ISSUE THREAD

**Issue by staranjeet** [pythonindia/wye#45]
For each model, there should be a ModelAdmin class, which will include important fields like
`list_per_page`, `list_display`, `exclude`, `list_display_links`, `search_fields`, `list_filter`.

**Comment by staranjeet** [comment]
I can work on this.

**Comment by vnbang2003** [comment]
This is not on high priority as it good to have feature. Do you mind to pick other issue which are of high priority ? Like #12 #13 #14

**Comment by curioswati** [comment]
@vnbang2003 I am willing to work on this issue.

**Comment by vnbang2003** [comment]
@curioswati Looking forward to see pull request.

**Comment by curioswati** [comment]
@staranjeet what should be the values for these fields?

**Comment by curioswati** [comment]
Okay, I have taken the values by my understanding. Please see if any changes are required. Do I need to attach screenshots for each model's admin interface with PR? And also do I need to write tests? And if yes then where should I write them as currently there are no tests written where I can add mine.

**Comment by vnbang2003** [comment]
@curioswati we don't need screenshot for this part as we can understand from Pull request.
But if you have screenshot that will easy all.
