### ISSUE TITLE
Disable E125 for flake8

### ISSUE THREAD

**Issue by shankisg** [pythonindia/wye#47]
While validating code using flake8, for code block below it throws **E125 continuation line does not distinguish itself from next logical line
** , can we disable it.

```python
class WorkshopToggleActive(
    views.LoginRequiredMixin, views.CsrfExemptMixin,
    views.JSONResponseMixin, generic.UpdateView):
```

**Comment by theskumar** [comment]
```python
class WorkshopToggleActive(
    views.LoginRequiredMixin, views.CsrfExemptMixin,
    views.JSONResponseMixin, generic.UpdateView):
```
vs 
```python
class WorkshopToggleActive(views.LoginRequiredMixin, views.CsrfExemptMixin,
                           views.JSONResponseMixin, generic.UpdateView):
```

I don't think there is much of the difference. 

I understand you might have a style of writing the code. I don't want to be sounding like a advocate of typographical design. But the standard there is for a reason, whether good or bad, they help in keep the code consistent and look same for every developer developers.

There are some tools/plugins like 

https://pypi.python.org/pypi/autopep8/
https://github.com/DamnWidget/anaconda

That will automatically format the code with flake8/pep8 guidelines. You can have them as part of git hooks or configured in editor.

**Comment by shankig** [comment]
Actually I am adapted to this way formatting the code, but will give try to your suggestion and see how it goes.

Will keep open this ticket for few days, if someone want to  express  there concern/suggestions.

**Comment by vnbang2003** [comment]
@shankisg Am closing it as i have seen any problem . In any case i have enable heroku build for project and that will take care of minor issues.
