### ISSUE TITLE
Student should be able to share feedback for workshop attended

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#51]
This is place holder for now. Need to discuss with all to take it forward.

Student should be able to share feedback for workshop attended

**Comment by kracekumar** [comment]
Students don't have login option and will the feedback url has to
unguessable to avoid spams.

On Sat, Oct 17, 2015 at 9:00 AM, Vijay <notifications@github.com> wrote:

> This is place holder for now. Need to discuss with all to take it forward.
>
> Student should be able to share feedback for workshop attended
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/51>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by theskumar** [comment]
- Should be able to to open/close the feedback at a specified time, as a workshop tutor. (?)
- Should use cookie based per browser, restrict voting to only once. (?)
- Should have a standard set of questions for feedback.
- The results should be visible to tutor and regional lead.

Add suggest to this initial set of requirements.
