### ISSUE TITLE
Moving all email template to common folder

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#57]
To make it simple i think it best to move all email template to common folder inside template direction.
I have created temp  folder  and add few place holder https://github.com/pythonindia/wye/tree/master/wye/templates/email_messages

We need to add both .txt and .html files there to make it simple for everyone to see content.

**Comment by harisibrahimkv** [comment]
Thanks @vnbang2003. @shankig I am not familiar with the project structure that much. If you could add the basic content for all the templates, I can review and edit it if necessary. For each template, I'll need to know whom the email is being sent to and what the email will be notifying that person of.

**Comment by shankisg** [comment]
@vnbang2003 @harisibrahimkv 

Let me add a pull request with required changes, then you guys can share feedback.  I think that will be good.

**Comment by vnbang2003** [comment]
@shankisg I have moved it hence closing it. Next fixes can go that directory
