### ISSUE TITLE
Home page to display gird to show stats

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#59]
In the home page we need to display gird showing number of organization registered, workshop completed, Tutor registered. In future we will have student register and etc.
There are two section for this feature 
1) Design the Grid in home page 
2) Write query to get this count from the system.

@Praseetha-KR Can you help us with first point  ?

**Comment by mascot6699** [comment]
@vnbang2003 May I work on the second part ?

**Comment by vnbang2003** [comment]
@mascot6699 it dependent of first part once that is done you can work.

**Comment by mascot6699** [comment]
:+1:

**Comment by Praseetha-KR** [comment]
Grid to show stats are included in #72

**Comment by vnbang2003** [comment]
@mascot6699 can you please complete second part ?

**Comment by mascot6699** [comment]
Yes I wil send a PR by 11pm

**Comment by mascot6699** [comment]
Query to show stats are included in #83

**Comment by mascot6699** [comment]
@vnbang2003 You may close this now.
