### ISSUE TITLE
Workshop listing page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#60]
We need workshop listing page more detailed information with different sections in it.
I have added 4 variable defining what am looking us.
@shankisg  Can you work on this as you have control on app better ?

**Comment by shankisg** [comment]
@vnbang2003 assign it to me, will take care.

**Comment by shankisg** [comment]
@vnbang2003 
Can you share the logic for
- workshop_feedback_pending
- workshop_withdrawn
- workshop_in_queue

We don't have any constants that define above status for workshop.

For  *workshop_feedback_pending* I can query  WorkshopFeedBack models to check if any entry for the workshop exists by checking the count.

**Comment by vnbang2003** [comment]
Logic is simple For every Complete workshop we want Both Presenter and requester to share feedback.
If there any completed workshop with no feedback from either part we don't allow them to request/submit any new workshop.

**Comment by shankisg** [comment]
@vnbang2003 
Let me complete #9 , then we can get back to this.

**Comment by vnbang2003** [comment]
@SudShekhar @shankisg  Just noticed that Workshop listing page design is changed hence this bug is not more valid. hence closing it.
