### ISSUE TITLE
UI: Add Navigation breadcrumb

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#61]
We need to add breadcrumbs section in the system so user know which page is in and can go back other pages easily.

**Comment by vnbang2003** [comment]
@ChillarAnand Can you help with this ?

**Comment by curioswati** [comment]
@vnbang2003 Can I work on this?

**Comment by vnbang2003** [comment]
If you interested to work on any project just drop comment saying you working on it. No need to ask permission.

Yes please work on it.

**Comment by curioswati** [comment]
okay. I am working on it.
