### ISSUE TITLE
Show upcoming workshops in home page.

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/wye#64]
It is good to show upcoming workshops on home page, if there are any.

**Comment by vnbang2003** [comment]
Am not in favour of it. We can show number and region details i don't want to show it.
In any case we send email when new workshop is requested with all details.

**Comment by harisibrahimkv** [comment]
I think this is a good one to have once we've established an initial momentum with workshops. Seeing many upcoming workshops on the front page will be a motivation for other organizations to sign up and conduct more workshops as well as for trainers to visit them more often.

**Comment by shankisg** [comment]
+1 @harisibrahimkv @ChillarAnand 

Yes, it would be good to display upcoming workshop, as well some of completed workshops(may be last 3 or 4 completed workshops).

**Comment by vnbang2003** [comment]
In the home page we will show number of upcoming workshop and other stats which is good .
If anyone is interested to know details let them login and see details of upcoming workshop.
further point can be discussed there #59  . Hence closing it as duplicate
