### ISSUE TITLE
Login with username or email

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/wye#69]
When sample data is generated, it creates superuser `admin/123123`. 
But we cant login to wye using username.

It is better if we allow login with username or email in general.

**Comment by vnbang2003** [comment]
I personal prefer email id so let stick to it. We can just change text inlogin page to say it as email id instead of username

**Comment by mascot6699** [comment]
@ChillarAnand  you can use `admin@fossevents.in` to login. We shall add this email also to the output of the sample_data.py and readme.md

**Comment by curioswati** [comment]
@mascot6699 Can I work on this?

**Comment by vnbang2003** [comment]
@curioswati We haven't accepted it as bug. Design of application is to work with email and i think we should continue with this to keep it simple.

**Comment by vnbang2003** [comment]
@curioswati If you have sometime you can help with this issue:  #45 .

**Comment by curioswati** [comment]
Yes. I get it. I was talking about changing the output of sample_data.py and readme.md. I have changed it.

**Comment by vnbang2003** [comment]
I still think let stick to email closing bug as won't fix.
