### ISSUE TITLE
Signup/Login panel UI

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#75]
Login/Signup Panel text is overlapping.
![screen shot 2015-10-23 at 10 23 57 am](https://cloud.githubusercontent.com/assets/316253/10684904/530e67de-7970-11e5-98b9-6f3611198716.png)

**Comment by vnbang2003** [comment]
@Praseetha-KR Can you help with this also ?

**Comment by vnbang2003** [comment]
Increase panel size. Doesn't look perfect but manageable

**Comment by Praseetha-KR** [comment]
Increased panel size & applied fluid width to input fields in #89
