### ISSUE TITLE
twiiter buzz

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#76]
When new workshop request is made we need to automatic tweet using pythonexpress twitter account.

**Comment by harisibrahimkv** [comment]
I can work on this.

On 23 October 2015 at 10:51, Vijay <notifications@github.com> wrote:

> When new workshop request is made we need to automatic tweet using
> pythonexpress twitter account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/76>.
>



-- 
Haris Ibrahim K. V.
http://sosaysharis.wordpress.com
@harisibrahimkv <http://twitter.com/harisibrahimkv>

**Comment by vnbang2003** [comment]
@harisibrahimkv We have tentative plan for Nov 1st beta live if so i will change milestone to v0.1 ?

**Comment by harisibrahimkv** [comment]
@vnbang2003 Yes. Could you make the scope clearer though? What is a `new workshop request`? Do you want the automatic tweet when:
1. A new workshop is created?
2. A Tutor is assigned?
3. Anything else?

**Comment by vnbang2003** [comment]
@harisibrahimkv to start this is good.

**Comment by harisibrahimkv** [comment]
Okai! :+1:

**Comment by kracekumar** [comment]
On Oct 23, 2015 11:03, "Haris Ibrahim K. V." <notifications@github.com>
wrote:
>
> @vnbang2003 Yes. Could you make the scope clearer though? What is a new
workshop request? Do you want the automatic tweet when:
> 1. A new workshop is created?
> 2. A Tutor is assigned?
> 3. Anything else?
>

This will look like a spam in twitter timeline and suggest auto tweet only
when a workshop is created.

**Comment by harisibrahimkv** [comment]
On 23 October 2015 at 11:16, Kracekumar Ramaraju <notifications@github.com>
wrote:

> On Oct 23, 2015 11:03, "Haris Ibrahim K. V." <notifications@github.com>
> wrote:
> >
> > @vnbang2003 Yes. Could you make the scope clearer though? What is a new
> workshop request? Do you want the automatic tweet when:
> > 1. A new workshop is created?
> > 2. A Tutor is assigned?
> > 3. Anything else?
> >
>
> This will look like a spam in twitter timeline and suggest auto tweet only
> when a workshop is created.
>

Hmm. Yeah, maybe. Let's start with just new workshop tweets and then see
what we need to tweak. I'll need to make an app on Twitter from the
PythonExpress account to do this. Either someone does this and puts the
keys in the server's environment or if I can be granted access, I'll do it.

-- 
Haris Ibrahim K. V.
http://sosaysharis.wordpress.com
@harisibrahimkv <http://twitter.com/harisibrahimkv>

**Comment by harisibrahimkv** [comment]
We need the following 4 environment variables set in the server's
.bashrc and exported as well.

```
export TWITTER_CONSUMER_KEY=""
export TWITTER_CONSUMER_SECRET=""
export TWITTER_ACCESS_TOKEN=""
export TWITTER_ACCESS_TOKEN_SECRET=""
```

**Comment by vnbang2003** [comment]
we already have pyconexpress account .Let use same twitter account.

**Comment by harisibrahimkv** [comment]
On 23 October 2015 at 11:38, Vijay <notifications@github.com> wrote:

> we already have pyconexpress account .Let use same twitter account.
>
Sure. But we need to make an `app` on https://apps.twitter.com/ and get all
the 4 tokens mentioned above. So someone who has access to the account
should do it and put the keys on the server.

-- 
Haris Ibrahim K. V.
http://sosaysharis.wordpress.com
@harisibrahimkv <http://twitter.com/harisibrahimkv>

**Comment by harisibrahimkv** [comment]
Pull request here: https://github.com/pythonindia/wye/pull/116
