### ISSUE TITLE
Workshop selection page

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#8]
This page should allow tutor to select workshop or admin can assign workshop to tutor

**Comment by shankig** [comment]
@vnbang2003 I can take it up. Let me know if its fine.

**Comment by vnbang2003** [comment]
@shankig let take one at a time . Any unassigned issues can be taken up.

**Comment by vnbang2003** [comment]
@shankig This page require some javascript work as this page needs to list of all workshop and tutor name of the region. Do let me know if you are fine if i ask UI expert to work on .

**Comment by shankig** [comment]
@vnbang2003 , workshop listing feature is implemented in #7 . I will implement the backend logic for tutor self assignment.

+1 . for UI expert. It will be good if you assign this task to me, I can take it up next.

**Comment by vnbang2003** [comment]
@shankig  Please assign to your self or else put comment you are working on it.

**Comment by shankig** [comment]
I am working on it.

**Comment by shankig** [comment]
@vnbang2003 
Per Workshop models we can have multiple presenter, I think we should restrict the number of presenter for a workshop. Your thought?

If  we restrict the number of presenter, so what should be the number.

**Comment by kracekumar** [comment]
My 2p. It is always possible to have multiple tutors for a workshop. Let's
not limit number of tutors for workshop now.

On Mon, Oct 12, 2015 at 5:50 PM, shanki <notifications@github.com> wrote:

> @vnbang2003 <https://github.com/vnbang2003>
> Per Workshop models we can have multiple presenter, I think we should
> restrict the number of presenter for a workshop. Your thought?
>
> If we restrict the number of presenter, so what should be the number.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/8#issuecomment-147379728>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by vnbang2003** [comment]
We will also have use case where workshop has multiple tracks(Parallel) we need to make changes to models to incorporate also.

**Comment by shankig** [comment]
Ok, that's fine. Then we should have 2 flag for,

- Tracking if workshop is over. No such attribute is available in Workshop model, like **completed**
- Stopping presenters to assign workshop to themselves. Where admin can go and change the flag.

**Comment by shankig** [comment]
Got new update in Workshop models **status** , this should work for me.

**Comment by vnbang2003** [comment]
@shankig  not clear with you point "Stopping presenters to assign workshop to themselves. Where admin can go and change the flag."

**Comment by shankig** [comment]
@vnbang2003  for now lets leave this topic. Let me complete this feature then we can discuss.

**Comment by shankisg** [comment]
Commit # 906c59bb7113063ec802376d7e3fe48d0455dd9a

**Comment by shankisg** [comment]
@vnbang2003 pls close this issue.
