### ISSUE TITLE
Production social account

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#82]
We need to get social app credentials for production setup.
We will support google, github and twitter ?
@kracekumar @vigneshsarma : Can one you take care of this ?

**Comment by vnbang2003** [comment]
@kracekumar @vigneshsarma can we plan for beta push this sunday  ?

**Comment by vnbang2003** [comment]
@kirang89 @theskumar @shankisg @ultimatecoder @curioswati @DESHRAJ @harisibrahimkv 
Guys,
    We are almost done with v0.1 milestone issue. Can you guys test and find issue if any.

@kracekumar @vigneshsarma
  Can you guys plan for push tomorrow with beta.pythonexpres.in so we can ask community to help us test and open issues so in next 15 days we are ready to make it live.

**Comment by kracekumar** [comment]
While setting up server we will do the required social media settings.

On Sat, Nov 7, 2015 at 12:53 PM, Vijay <notifications@github.com> wrote:

> @kirang89 <https://github.com/kirang89> @theskumar
> <https://github.com/theskumar> @shankisg <https://github.com/shankisg>
> @ultimatecoder <https://github.com/ultimatecoder> @curioswati
> <https://github.com/curioswati> @DESHRAJ <https://github.com/DESHRAJ>
> @harisibrahimkv <https://github.com/harisibrahimkv>
> Guys,
> We are almost done with v0.1 milestone issue. Can you guys test and find
> issue if any.
>
> @kracekumar <https://github.com/kracekumar> @vigneshsarma
> <https://github.com/vigneshsarma>
> Can you guys plan for push tomorrow with beta.pythonexpres.in so we can
> ask community to help us test and open issues so in next 15 days we are
> ready to make it live.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/wye/issues/82#issuecomment-154648904>.
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com
