### ISSUE TITLE
Change signup page fields

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#88]
We need to change signup page to request
1) Email 
2) Password (Only once) 
3) First name 
4) Last Name
5) Mobile no (let add validation)

@DESHRAJ  : Can you help with this as you were handling this part ?

**Comment by vnbang2003** [comment]
@ChillarAnand Can you please help us with this change in model ?

**Comment by DESHRAJ** [comment]
Yeah sure I can. Sorry, I was at home for last 7 days so I was unable to work on the project. :)

**Comment by vnbang2003** [comment]
Closing this bug
