### ISSUE TITLE
Not able to create region lead

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/wye#90]
In region page (http://127.0.0.1:8000/region/), create region lead(http://127.0.0.1:8000/region/lead/create/)  is not working.

![wye](https://cloud.githubusercontent.com/assets/4463796/10709763/f1885626-7a57-11e5-8be0-f7b107989155.png)

**Comment by vnbang2003** [comment]
Fixed it. Latest code check in with work.

**Comment by ChillarAnand** [comment]
:+1:
