### ISSUE TITLE
HTML Email Template

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#99]
For HTML emails we need to design base template so all other html email  can extend and change content .
The base template needs to be in /template/email_messages/

@Praseetha-KR : Can you help us with this  ?

**Comment by vnbang2003** [comment]
@Praseetha-KR I have added template example in /template/email_messages/organisaiton/new.html
Can you help us update the html with better head and footer .
Even the Logo in HTML email is can be smaller.

**Comment by Praseetha-KR** [comment]
I have added mailer base layout in /template/email_messages/layout.html #163

**Comment by vnbang2003** [comment]
@harisibrahimkv Can you help us moving all html email template to format share by @Praseetha-KR ?
@shankisg Can you create dummy .html and .txt file for email so Haris can work on content for the same.
